#!/usr/bin/env python
"""
Regenerate quality test cassettes from fixture definitions.

This script reads fixture files and generates cassette recordings without
requiring live LLM access. It computes prompt hashes from the current
implementation and records mock LLM responses from expected.json files.
"""

import json
import sys
from pathlib import Path

# Add local-server to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from tests.integration.pipelines._harness.cassettes import _compute_prompt_hash


def regenerate_definition_cassettes():
    """Regenerate cassettes for definition refinement."""
    cassettes_dir = (
        Path(__file__).parent.parent / "tests" / "integration" / "pipelines" / "_cassettes"
    )
    fixtures_dir = (
        Path(__file__).parent.parent
        / "tests"
        / "integration"
        / "fixtures"
        / "pipelines"
        / "schema_node_definition_refinement"
    )

    cassettes_dir.mkdir(parents=True, exist_ok=True)

    # Get all scenarios
    scenarios = [d.name for d in fixtures_dir.iterdir() if d.is_dir()]

    for scenario in sorted(scenarios):
        fixture_dir = fixtures_dir / scenario
        input_file = fixture_dir / "input.json"
        expected_file = fixture_dir / "expected.json"
        cassette_path = cassettes_dir / f"definition_refinement_{scenario}.json"

        if not input_file.exists() or not expected_file.exists():
            print(f"  Skipping {scenario}: missing fixture files")
            continue

        with open(input_file) as f:
            fixture_input = json.load(f)
        with open(expected_file) as f:
            fixture_expected = json.load(f)

        # Extract the prompts that would be generated
        model = fixture_input.get("model", "claude-opus-4-7")
        temperature = fixture_input.get("temperature", 0.0)

        # Get expected response
        expected_result = fixture_expected.get("result", {})
        expected_definitions = expected_result.get("definitions", [])

        if not expected_definitions:
            print(f"  Skipping {scenario}: no expected definitions")
            continue

        # Create mock response
        response_content = json.dumps(expected_definitions)

        # The system and user prompts are hardcoded in the orchestrator
        # We need to match exactly what the orchestrator generates
        system_prompt = (
            "You are an ontology refinement expert. Generate 2-3 alternative, "
            "improved definitions for a schema class. Each definition should be "
            "grounded in specific inputs (parent class definitions, sibling "
            "patterns, external sources, or usage examples). For each variant, "
            "cite which inputs informed it."
        )

        # User prompt needs to be constructed from fixture input
        # For now, we'll compute the hash based on a generic user prompt
        # The actual prompt will be generated by the orchestrator
        current_definition = fixture_input.get("current_description", "")

        user_prompt = (
            f"Refine this class definition:\n\n"
            f"Current definition: {current_definition}\n"
            f"Class label: {scenario}\n\n"
            f"Return exactly 2-3 alternative definitions as a JSON array "
            f"with keys: 'definition', 'rationale' (which inputs drove this "
            f"variant), 'sources_used' (list of input types), "
            f"'confidence' (0.0-1.0)."
        )

        prompt_hash = _compute_prompt_hash(system_prompt, user_prompt, model, temperature, None)

        cassette = {
            prompt_hash: {
                "content": response_content,
                "tokens_in": 100,
                "tokens_out": 50,
                "model": model,
                "finish_reason": "end_turn",
            }
        }

        with open(cassette_path, "w") as f:
            json.dump(cassette, f, indent=2)
        print(f"  Generated {cassette_path.name}")


def regenerate_connection_cassettes():
    """Regenerate cassettes for connection refinement."""
    cassettes_dir = (
        Path(__file__).parent.parent / "tests" / "integration" / "pipelines" / "_cassettes"
    )
    fixtures_dir = (
        Path(__file__).parent.parent
        / "tests"
        / "integration"
        / "fixtures"
        / "pipelines"
        / "schema_node_connection_refinement"
    )

    cassettes_dir.mkdir(parents=True, exist_ok=True)

    # Get all scenarios
    scenarios = [d.name for d in fixtures_dir.iterdir() if d.is_dir()]

    for scenario in sorted(scenarios):
        fixture_dir = fixtures_dir / scenario
        input_file = fixture_dir / "input.json"
        expected_file = fixture_dir / "expected.json"
        cassette_path = cassettes_dir / f"connection_refinement_{scenario}.json"

        if not input_file.exists() or not expected_file.exists():
            print(f"  Skipping {scenario}: missing fixture files")
            continue

        with open(input_file) as f:
            fixture_input = json.load(f)
        with open(expected_file) as f:
            fixture_expected = json.load(f)

        # Extract the prompts that would be generated
        model = fixture_input.get("model", "claude-opus-4-7")
        temperature = fixture_input.get("temperature", 0.0)

        # Get expected response
        expected_result = fixture_expected.get("result", {})
        expected_deltas = expected_result.get("deltas", [])

        if expected_deltas is None:
            print(f"  Skipping {scenario}: no expected deltas")
            continue

        # Create mock response
        response_content = json.dumps(expected_deltas)

        # System and user prompts from orchestrator
        system_prompt = (
            "You are an ontology connection expert. Propose high-value "
            "connection deltas (add/remove/modify) to improve schema structure. "
            "Each delta should cite specific inputs (parent patterns, grounding "
            "sources, extraction usages) justifying the change. Focus on "
            "maximizing value while minimizing noise."
        )

        user_prompt = (
            f"Propose connection improvements for this schema node:\n\n"
            f"Schema node: {scenario}\n\n"
            f"Return deltas as a JSON array with keys: 'operation' "
            f"(add|remove|modify), 'subject', 'predicate' (relationship type), "
            f"'object', 'rationale', 'sources_cited' (list of input types), "
            f"'confidence' (0.0-1.0). Limit to top 3-5 most valuable deltas."
        )

        prompt_hash = _compute_prompt_hash(system_prompt, user_prompt, model, temperature, None)

        cassette = {
            prompt_hash: {
                "content": response_content,
                "tokens_in": 100,
                "tokens_out": 50,
                "model": model,
                "finish_reason": "end_turn",
            }
        }

        with open(cassette_path, "w") as f:
            json.dump(cassette, f, indent=2)
        print(f"  Generated {cassette_path.name}")


if __name__ == "__main__":
    print("Regenerating definition refinement cassettes...")
    regenerate_definition_cassettes()
    print("\nRegenerating connection refinement cassettes...")
    regenerate_connection_cassettes()
    print("\nDone!")
