"""add pipeline_configurations and pipeline_executions tables

Revision ID: 001
Revises:
Create Date: 2026-03-28 21:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configurations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_configurations_pipeline', 'pipeline_configurations', ['pipeline'], unique=False)
    op.create_table('pipeline_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_config_id', sa.String(length=36), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_executions_pipeline_config_id', 'pipeline_executions', ['pipeline_config_id'], unique=False)
    op.create_index('ix_pipeline_executions_timestamp', 'pipeline_executions', ['timestamp'], unique=False)
    op.create_index('ix_executions_config_timestamp', 'pipeline_executions', ['pipeline_config_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_executions_config_timestamp', table_name='pipeline_executions')
    op.drop_index('ix_pipeline_executions_timestamp', table_name='pipeline_executions')
    op.drop_index('ix_pipeline_executions_pipeline_config_id', table_name='pipeline_executions')
    op.drop_table('pipeline_executions')
    op.drop_index('ix_pipeline_configurations_pipeline', table_name='pipeline_configurations')
    op.drop_table('pipeline_configurations')
    # ### end Alembic commands ###
