"""add_user_pipeline_configurations

Revision ID: 0eb7be4413f3
Revises: 84a7f3b2d9c1
Create Date: 2026-06-10 12:40:11.750786

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0eb7be4413f3'
down_revision = '84a7f3b2d9c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('config_ref', sa.String(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('implementation_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_pipeline_configurations_config_ref'),
        'pipeline_configurations', ['config_ref'], unique=False,
    )
    op.create_index(
        op.f('ix_pipeline_configurations_pipeline_type'),
        'pipeline_configurations', ['pipeline_type'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_pipeline_configurations_pipeline_type'),
        table_name='pipeline_configurations',
    )
    op.drop_index(
        op.f('ix_pipeline_configurations_config_ref'),
        table_name='pipeline_configurations',
    )
    op.drop_table('pipeline_configurations')
    # ### end Alembic commands ###
