"""add seed column to pipeline_configurations

Revision ID: b3e4c9d7f2a1
Revises: 619a27b89a15
Create Date: 2026-05-08 20:15:00.123456

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b3e4c9d7f2a1"
down_revision = "619a27b89a15"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pipeline_configurations", sa.Column("seed", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pipeline_configurations", "seed")
    # ### end Alembic commands ###
