// =========================================================================
// Context Studio — sample workspace data (molgraph-research)
// Hierarchy: Taxonomy → ConceptScheme → Class → Individual
// Plus PropertyDefinitions and Relationships (triples).
// =========================================================================
window.CS_DATA = (() => {
  const taxonomies = [
    {
      id: "tax_life",
      title: "Life Sciences",
      domain: "life",
      description: "Biological and biomedical knowledge organisation",
      version: 4,
      classes: 11,
      individuals: 142,
      updated: "2026-05-19",
    },
    {
      id: "tax_climate",
      title: "Climate & Environment",
      domain: "climate",
      description: "Earth systems, emissions, and sustainability concepts",
      version: 2,
      classes: 7,
      individuals: 98,
      updated: "2026-05-17",
    },
    {
      id: "tax_sw",
      title: "Software Engineering",
      domain: "software",
      description: "Patterns, architectures, and engineering practices",
      version: 1,
      classes: 4,
      individuals: 27,
      updated: "2026-05-08",
    },
  ];

  const concept_schemes = [
    {
      id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      title: "Cellular Biology",
      domain: "life",
      description: "Cells, organelles, and tissue-level concepts",
      version: 3,
      classes: 6,
    },
    {
      id: "sch_genomics",
      taxonomy_id: "tax_life",
      title: "Genomics & Proteomics",
      domain: "life",
      description: "Genes, variants, and gene products",
      version: 5,
      classes: 3,
    },
    {
      id: "sch_pathways",
      taxonomy_id: "tax_life",
      title: "Molecular Pathways",
      domain: "life",
      description: "Reaction networks and signalling cascades",
      version: 1,
      classes: 2,
    },
    {
      id: "sch_emissions",
      taxonomy_id: "tax_climate",
      title: "Emissions",
      domain: "climate",
      description: "Greenhouse gases and forcing agents",
      version: 2,
      classes: 2,
    },
    {
      id: "sch_impacts",
      taxonomy_id: "tax_climate",
      title: "Climate Impacts",
      domain: "climate",
      description: "Observed and projected effects",
      version: 2,
      classes: 3,
    },
    {
      id: "sch_solutions",
      taxonomy_id: "tax_climate",
      title: "Mitigation & Solutions",
      domain: "climate",
      description: "Renewables and carbon-removal strategies",
      version: 1,
      classes: 2,
    },
    {
      id: "sch_arch",
      taxonomy_id: "tax_sw",
      title: "Architecture Patterns",
      domain: "software",
      description: "Macro-architectural styles",
      version: 1,
      classes: 3,
    },
    {
      id: "sch_testing",
      taxonomy_id: "tax_sw",
      title: "Testing & QA",
      domain: "software",
      description: "Approaches to verifying behaviour",
      version: 0,
      classes: 1,
    },
  ];

  const classes = [
    // Cellular Biology
    {
      id: "cls_cell",
      title: "Cell",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      description: "Basic structural and functional unit of life",
      individuals: 8,
      version: 12,
    },
    {
      id: "cls_nucleus",
      title: "Nucleus",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      description: "Membrane-bound organelle containing genetic material",
      individuals: 5,
      version: 3,
    },
    {
      id: "cls_mito",
      title: "Mitochondrion",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      description: "Energy-producing organelle",
      individuals: 4,
      version: 4,
    },
    {
      id: "cls_membrane",
      title: "Cell Membrane",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      description: "Phospholipid bilayer boundary",
      individuals: 1,
      version: 1,
    },
    {
      id: "cls_stem",
      title: "Stem Cell",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      description: "Undifferentiated progenitor cell",
      individuals: 6,
      version: 6,
    },
    {
      id: "cls_neuron",
      title: "Neuron",
      concept_scheme_id: "sch_cell_bio",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_cell",
      description: "Electrically excitable cell",
      individuals: 3,
      version: 5,
    },
    // Genomics & Proteomics
    {
      id: "cls_gene",
      title: "Gene",
      concept_scheme_id: "sch_genomics",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      description: "DNA sequence encoding a product",
      individuals: 47,
      version: 9,
    },
    {
      id: "cls_variant",
      title: "Variant",
      concept_scheme_id: "sch_genomics",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: "cls_gene",
      description: "Genetic variation in a population",
      individuals: 12,
      version: 2,
    },
    {
      id: "cls_protein",
      title: "Protein",
      concept_scheme_id: "sch_genomics",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      description: "Functional gene product",
      individuals: 38,
      version: 7,
    },
    // Pathways
    {
      id: "cls_pathway",
      title: "Pathway",
      concept_scheme_id: "sch_pathways",
      taxonomy_id: "tax_life",
      domain: "life",
      parent_class_id: null,
      description: "Sequence of molecular interactions",
      individuals: 18,
      version: 3,
    },
    // Climate Emissions
    {
      id: "cls_co2",
      title: "CO\u2082",
      concept_scheme_id: "sch_emissions",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      description: "Carbon dioxide",
      individuals: 14,
      version: 4,
    },
    {
      id: "cls_methane",
      title: "Methane",
      concept_scheme_id: "sch_emissions",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      description: "Potent short-lived greenhouse gas",
      individuals: 6,
      version: 2,
    },
    // Climate Impacts
    {
      id: "cls_warming",
      title: "Global Warming",
      concept_scheme_id: "sch_impacts",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      description: "Long-term temperature increase",
      individuals: 9,
      version: 4,
    },
    {
      id: "cls_sealevel",
      title: "Sea Level Rise",
      concept_scheme_id: "sch_impacts",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: "cls_warming",
      description: "Ocean expansion and ice melt",
      individuals: 5,
      version: 1,
    },
    {
      id: "cls_deforest",
      title: "Deforestation",
      concept_scheme_id: "sch_impacts",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      description: "Forest cover reduction",
      individuals: 11,
      version: 2,
    },
    // Solutions
    {
      id: "cls_renew",
      title: "Renewable Energy",
      concept_scheme_id: "sch_solutions",
      taxonomy_id: "tax_climate",
      domain: "climate",
      parent_class_id: null,
      description: "Solar, wind, and hydro sources",
      individuals: 12,
      version: 5,
    },
    // SW Architecture
    {
      id: "cls_hex",
      title: "Hexagonal Architecture",
      concept_scheme_id: "sch_arch",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      description: "Ports and adapters pattern",
      individuals: 4,
      version: 2,
    },
    {
      id: "cls_ddd",
      title: "Domain-Driven Design",
      concept_scheme_id: "sch_arch",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      description: "Model-centric development approach",
      individuals: 3,
      version: 1,
    },
    {
      id: "cls_micro",
      title: "Microservices",
      concept_scheme_id: "sch_arch",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      description: "Service decomposition pattern",
      individuals: 12,
      version: 3,
    },
    // Testing
    {
      id: "cls_unit",
      title: "Unit Test",
      concept_scheme_id: "sch_testing",
      taxonomy_id: "tax_sw",
      domain: "software",
      parent_class_id: null,
      description: "Isolated function or class test",
      individuals: 8,
      version: 0,
    },
  ];

  const individuals = [
    {
      id: "ind_brca1",
      title: "BRCA1",
      description: "BRCA1 DNA repair gene",
      class_ids: ["cls_gene"],
      source: "NCBI",
      confidence: 0.99,
      updated: "2026-05-19",
      version: 2,
    },
    {
      id: "ind_tp53",
      title: "TP53",
      description: "Tumour-protein p53 gene",
      class_ids: ["cls_gene"],
      source: "NCBI",
      confidence: 0.98,
      updated: "2026-05-18",
      version: 1,
    },
    {
      id: "ind_egfr",
      title: "EGFR",
      description: "Epidermal growth factor receptor gene",
      class_ids: ["cls_gene"],
      source: "UniProt",
      confidence: 0.97,
      updated: "2026-05-12",
      version: 1,
    },
    {
      id: "ind_p53",
      title: "p53 protein",
      description: "Tumour suppressor protein",
      class_ids: ["cls_protein"],
      source: "UniProt",
      confidence: 0.99,
      updated: "2026-05-19",
      version: 3,
    },
    {
      id: "ind_apop",
      title: "Apoptosis pathway",
      description: "Programmed cell death",
      class_ids: ["cls_pathway"],
      source: "Reactome",
      confidence: 0.95,
      updated: "2026-05-02",
      version: 1,
    },
    {
      id: "ind_co2_atm",
      title: "Atmospheric CO\u2082 (2025)",
      description: "Annual mean atmospheric CO\u2082",
      class_ids: ["cls_co2"],
      source: "NOAA",
      confidence: 1.0,
      updated: "2026-05-20",
      version: 2,
    },
    {
      id: "ind_amazon",
      title: "Amazon deforestation",
      description: "Amazon rainforest forest loss",
      class_ids: ["cls_deforest"],
      source: "WWF",
      confidence: 0.93,
      updated: "2026-05-08",
      version: 4,
    },
    {
      id: "ind_solar_us",
      title: "US Solar Capacity",
      description: "United States installed solar PV capacity",
      class_ids: ["cls_renew"],
      source: "EIA",
      confidence: 0.96,
      updated: "2026-05-15",
      version: 1,
    },
    {
      id: "ind_hex_alistair",
      title: "Cockburn\u2019s Hexagonal",
      description: "Original 2005 essay",
      class_ids: ["cls_hex"],
      source: "Manual",
      confidence: 1.0,
      updated: "2026-04-14",
      version: 1,
    },
    {
      id: "ind_evans_ddd",
      title: "Evans, 2003",
      description: "The original DDD blue book",
      class_ids: ["cls_ddd"],
      source: "Manual",
      confidence: 1.0,
      updated: "2026-04-14",
      version: 1,
    },
    {
      id: "ind_brca2",
      title: "BRCA2",
      description: "Breast cancer type 2 susceptibility",
      class_ids: ["cls_gene"],
      source: "NCBI",
      confidence: 0.99,
      updated: "2026-05-19",
      version: 1,
    },
    {
      id: "ind_myc",
      title: "MYC",
      description: "MYC proto-oncogene",
      class_ids: ["cls_gene"],
      source: "NCBI",
      confidence: 0.98,
      updated: "2026-05-18",
      version: 1,
    },
    {
      id: "ind_hbb",
      title: "HBB",
      description: "Hemoglobin subunit beta",
      class_ids: ["cls_gene", "cls_variant"],
      source: "NCBI",
      confidence: 0.97,
      updated: "2026-05-12",
      version: 2,
    },
    {
      id: "ind_methane_atm",
      title: "Atmospheric CH\u2084 (2025)",
      description: "Tropospheric methane mean",
      class_ids: ["cls_methane"],
      source: "NOAA",
      confidence: 1.0,
      updated: "2026-05-20",
      version: 2,
    },
    {
      id: "ind_iss_solar",
      title: "ISS solar arrays",
      description: "Photovoltaic panels on ISS",
      class_ids: ["cls_renew"],
      source: "NASA",
      confidence: 1.0,
      updated: "2026-05-03",
      version: 1,
    },
    {
      id: "ind_neuron_pyr",
      title: "Pyramidal neuron",
      description: "Cortical excitatory neuron",
      class_ids: ["cls_neuron"],
      source: "ConceptNet",
      confidence: 0.92,
      updated: "2026-05-11",
      version: 1,
    },
  ];

  const property_definitions = [
    {
      id: "prop_has_part",
      identifier: "has_part",
      title: "Has Part",
      description: "Mereological containment",
      is_relevant: true,
      origin: "manual",
      version: 3,
      used_by: 7,
    },
    {
      id: "prop_part_of",
      identifier: "part_of",
      title: "Is Part Of",
      description: "Inverse of has_part",
      is_relevant: true,
      origin: "manual",
      version: 2,
      used_by: 4,
    },
    {
      id: "prop_encodes",
      identifier: "encodes",
      title: "Encodes",
      description: "Gene encodes a protein",
      is_relevant: true,
      origin: "manual",
      version: 4,
      used_by: 38,
    },
    {
      id: "prop_emits",
      identifier: "emits",
      title: "Emits",
      description: "Source emits substance",
      is_relevant: true,
      origin: "pipeline:pubmed",
      version: 1,
      used_by: 11,
    },
    {
      id: "prop_related_to",
      identifier: "related_to",
      title: "Related To",
      description: "Generic association",
      is_relevant: null,
      origin: "auto",
      version: 0,
      used_by: 2,
    },
    {
      id: "prop_mentioned_in",
      identifier: "mentioned_in",
      title: "Mentioned In",
      description: "Surface co-mention",
      is_relevant: false,
      origin: "pipeline:arxiv",
      version: 0,
      used_by: 0,
    },
    {
      id: "prop_causes",
      identifier: "causes",
      title: "Causes",
      description: "Causal connection",
      is_relevant: true,
      origin: "manual",
      version: 1,
      used_by: 6,
    },
    {
      id: "prop_located_in",
      identifier: "located_in",
      title: "Located In",
      description: "Spatial containment",
      is_relevant: null,
      origin: "auto",
      version: 0,
      used_by: 3,
    },
  ];

  const relationships = [
    {
      id: "rel_a921",
      source_id: "cls_cell",
      target_id: "cls_nucleus",
      property_definition_id: "prop_has_part",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-04",
    },
    {
      id: "rel_a922",
      source_id: "cls_cell",
      target_id: "cls_mito",
      property_definition_id: "prop_has_part",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-04",
    },
    {
      id: "rel_a923",
      source_id: "cls_cell",
      target_id: "cls_membrane",
      property_definition_id: "prop_has_part",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-04",
    },
    {
      id: "rel_b302",
      source_id: "cls_gene",
      target_id: "cls_protein",
      property_definition_id: "prop_encodes",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-08",
    },
    {
      id: "rel_e811",
      source_id: "ind_brca1",
      target_id: "ind_p53",
      property_definition_id: "prop_related_to",
      source: "pubmed",
      confidence: 0.92,
      created: "2026-04-26",
    },
    {
      id: "rel_c104",
      source_id: "cls_protein",
      target_id: "cls_pathway",
      property_definition_id: "prop_part_of",
      source: "reactome",
      confidence: 0.96,
      created: "2026-04-12",
    },
    {
      id: "rel_d557",
      source_id: "cls_deforest",
      target_id: "cls_co2",
      property_definition_id: "prop_emits",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-14",
    },
    {
      id: "rel_f209",
      source_id: "ind_amazon",
      target_id: "ind_co2_atm",
      property_definition_id: "prop_emits",
      source: "wwf",
      confidence: 0.85,
      created: "2026-04-18",
    },
    {
      id: "rel_g441",
      source_id: "cls_warming",
      target_id: "cls_sealevel",
      property_definition_id: "prop_causes",
      source: "manual",
      confidence: 1.0,
      created: "2026-03-22",
    },
  ];

  const pipelines = [
    {
      id: "pl_pubmed_genes",
      name: "pubmed_genes",
      description: "Extract gene and protein mentions from PubMed abstracts",
      status: "running",
      target: "Schema + Data",
      lastRun: "now",
      avgRunMs: 184000,
      progress: 38,
      flow: [
        { kind: "source", name: "PubMed", sub: "pubmed_e_utils", ic: "reference" },
        { kind: "extract", name: "NER", sub: "gpt-4o-mini", ic: "sparkle" },
        { kind: "resolve", name: "Resolve", sub: "NCBI Gene", ic: "link" },
        { kind: "write", name: "Knowledge Graph", sub: "Genes / Proteins", ic: "database" },
      ],
      recent: { ingested: 412, created: 38, updated: 17, errors: 0 },
      tags: ["scheduled", "weekly"],
    },
    {
      id: "pl_ipcc_climate",
      name: "ipcc_ar6",
      description: "Build taxonomy structure from IPCC chapter headings",
      status: "success",
      target: "Schema",
      lastRun: "12m ago",
      avgRunMs: 312000,
      progress: 100,
      flow: [
        { kind: "source", name: "IPCC AR6", sub: "PDF corpus", ic: "doc" },
        { kind: "extract", name: "Topic mining", sub: "BERTopic", ic: "sparkle" },
        { kind: "resolve", name: "Concept align", sub: "GLOSSARY", ic: "link" },
        { kind: "write", name: "Knowledge Graph", sub: "Climate tax", ic: "database" },
      ],
      recent: { ingested: 28, created: 6, updated: 2, errors: 0 },
      tags: ["manual"],
    },
    {
      id: "pl_arxiv_se",
      name: "arxiv_cs_se",
      description: "Surface software architecture patterns from recent arXiv",
      status: "idle",
      target: "Schema + Data",
      lastRun: "2h ago",
      avgRunMs: 96000,
      progress: 0,
      flow: [
        { kind: "source", name: "arXiv cs.SE", sub: "OAI-PMH", ic: "reference" },
        { kind: "extract", name: "Concept extract", sub: "claude-haiku", ic: "sparkle" },
        { kind: "resolve", name: "Dedup", sub: "embeddings", ic: "link" },
        { kind: "write", name: "Knowledge Graph", sub: "SW patterns", ic: "database" },
      ],
      recent: { ingested: 156, created: 4, updated: 11, errors: 1 },
      tags: ["scheduled"],
    },
    {
      id: "pl_eia_solar",
      name: "eia_renewables",
      description: "Pull renewable capacity figures into Climate individuals",
      status: "failed",
      target: "Data",
      lastRun: "3h ago",
      avgRunMs: 48000,
      progress: 0,
      flow: [
        { kind: "source", name: "EIA API", sub: "eia.gov/v2", ic: "globe" },
        { kind: "extract", name: "Schema map", sub: "jq + LLM", ic: "sparkle" },
        { kind: "resolve", name: "Match class", sub: "cls_renew", ic: "link" },
        { kind: "write", name: "Individuals", sub: "cls_renew", ic: "database" },
      ],
      recent: { ingested: 0, created: 0, updated: 0, errors: 1 },
      tags: ["api"],
    },
    {
      id: "pl_wikipedia",
      name: "wikipedia_links",
      description: "Surface external references for new concepts via Wikipedia and Wikidata",
      status: "idle",
      target: "Schema",
      lastRun: "yesterday",
      avgRunMs: 220000,
      progress: 0,
      flow: [
        { kind: "source", name: "Wikipedia", sub: "API + dumps", ic: "globe" },
        { kind: "extract", name: "Link extract", sub: "regex + LLM", ic: "sparkle" },
        { kind: "resolve", name: "Wikidata", sub: "QIDs", ic: "link" },
        { kind: "write", name: "Class refs", sub: "external_references", ic: "database" },
      ],
      recent: { ingested: 1142, created: 0, updated: 84, errors: 0 },
      tags: ["scheduled", "nightly"],
    },
    {
      id: "pl_uniprot",
      name: "uniprot_proteins",
      description: "Refresh protein descriptors from UniProt",
      status: "success",
      target: "Data",
      lastRun: "yesterday",
      avgRunMs: 142000,
      progress: 100,
      flow: [
        { kind: "source", name: "UniProt", sub: "REST", ic: "reference" },
        { kind: "extract", name: "Schema map", sub: "json+jq", ic: "sparkle" },
        { kind: "resolve", name: "Gene linkage", sub: "ind_brca1…", ic: "link" },
        { kind: "write", name: "Individuals", sub: "cls_protein", ic: "database" },
      ],
      recent: { ingested: 312, created: 8, updated: 23, errors: 0 },
      tags: ["scheduled", "daily"],
    },
  ];

  const activity = [
    {
      kind: "create",
      who: "pipeline · pubmed",
      what: "Created class",
      subject: "cls_variant",
      meta: "sch_genomics · life",
      when: "2m",
    },
    {
      kind: "create",
      who: "pipeline · pubmed",
      what: "Created property_definition",
      subject: "prop_encodes",
      meta: "v4 · 38 used_by",
      when: "2m",
    },
    {
      kind: "update",
      who: "maya@studio",
      what: "Updated relationship",
      subject: "rel_e811",
      meta: "BRCA1 → related_to → p53",
      when: "8m",
    },
    {
      kind: "run",
      who: "scheduler",
      what: "Started pipeline",
      subject: "pl_pubmed_genes",
      meta: "step 2/4 NER",
      when: "12m",
    },
    {
      kind: "create",
      who: "maya@studio",
      what: "Created relationship",
      subject: "rel_a921",
      meta: "Cell hasPart Nucleus",
      when: "34m",
    },
    {
      kind: "run",
      who: "scheduler",
      what: "Pipeline completed",
      subject: "pl_uniprot",
      meta: "+ 8 individuals · ~23 upd",
      when: "1h",
    },
    {
      kind: "delete",
      who: "maya@studio",
      what: "Removed individual",
      subject: "ind_co2_test",
      meta: "cls_co2 · cascade ×3",
      when: "1h",
    },
    {
      kind: "update",
      who: "maya@studio",
      what: "Renamed property",
      subject: "prop_mentioned_in",
      meta: "from mentions",
      when: "2h",
    },
  ];

  const reference_sources = [
    {
      id: "src_pubmed",
      name: "PubMed",
      kind: "api",
      url: "eutils.ncbi.nlm.nih.gov",
      pipelines: 2,
      last: "now",
      status: "ok",
    },
    {
      id: "src_uniprot",
      name: "UniProt",
      kind: "api",
      url: "rest.uniprot.org",
      pipelines: 1,
      last: "yesterday",
      status: "ok",
    },
    {
      id: "src_arxiv",
      name: "arXiv cs.SE",
      kind: "api",
      url: "export.arxiv.org/oai2",
      pipelines: 1,
      last: "2h",
      status: "ok",
    },
    {
      id: "src_eia",
      name: "EIA API",
      kind: "api",
      url: "api.eia.gov/v2",
      pipelines: 1,
      last: "3h",
      status: "fail",
    },
    {
      id: "src_ipcc",
      name: "IPCC AR6",
      kind: "corpus",
      url: "ar6_wg1.pdf · 4 chapters",
      pipelines: 1,
      last: "12m",
      status: "ok",
    },
    {
      id: "src_wikidata",
      name: "Wikidata",
      kind: "api",
      url: "query.wikidata.org/sparql",
      pipelines: 1,
      last: "yesterday",
      status: "ok",
    },
    {
      id: "src_reactome",
      name: "Reactome",
      kind: "dataset",
      url: "reactome.org/download",
      pipelines: 0,
      last: "—",
      status: "idle",
    },
  ];

  // Sparkline data — 12-point series per stat tile
  const sparks = {
    taxonomies: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
    classes: [16, 17, 17, 18, 18, 18, 18, 19, 20, 20, 21, 22],
    individuals: [201, 210, 215, 223, 230, 235, 247, 250, 252, 258, 262, 267],
    pipelines: [4, 5, 5, 6, 6, 7, 8, 9, 10, 10, 11, 11],
    ingestRate: [120, 95, 180, 210, 240, 198, 280, 322, 350, 412, 380, 412],
  };

  return {
    taxonomies,
    concept_schemes,
    classes,
    individuals,
    property_definitions,
    relationships,
    pipelines,
    activity,
    reference_sources,
    sparks,
    workspace: {
      name: "molgraph-research",
      path: "~/Projects/molgraph-research",
      branch: "main",
      version: "v0.2.0",
      last_sync: "2m ago",
    },
  };
})();
