/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/layers/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Layer Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        get: operations["find_layer_unsupported_method_delete_api_layers_find_get"];
        /**
         * Find Layer Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        put: operations["find_layer_unsupported_method_delete_api_layers_find_put"];
        /**
         * Find Layer Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        post: operations["find_layer_unsupported_method_delete_api_layers_find_post"];
        /**
         * Find Layer Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        delete: operations["find_layer_unsupported_method_delete_api_layers_find_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Layers */
        get: operations["list_layers_api_layers__get"];
        put?: never;
        /** Create Layer */
        post: operations["create_layer_api_layers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layer */
        get: operations["get_layer_api_layers__id__get"];
        /** Update Layer */
        put: operations["update_layer_api_layers__id__put"];
        post?: never;
        /** Delete Layer */
        delete: operations["delete_layer_api_layers__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Domain Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        get: operations["find_domain_unsupported_method_delete_api_domains_find_get"];
        /**
         * Find Domain Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        put: operations["find_domain_unsupported_method_delete_api_domains_find_put"];
        /**
         * Find Domain Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        post: operations["find_domain_unsupported_method_delete_api_domains_find_post"];
        /**
         * Find Domain Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        delete: operations["find_domain_unsupported_method_delete_api_domains_find_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Domains */
        get: operations["list_domains_api_domains__get"];
        put?: never;
        /** Create Domain */
        post: operations["create_domain_api_domains__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Domain */
        get: operations["get_domain_api_domains__id__get"];
        /** Update Domain */
        put: operations["update_domain_api_domains__id__put"];
        post?: never;
        /** Delete Domain */
        delete: operations["delete_domain_api_domains__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Term Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        get: operations["find_term_unsupported_method_delete_api_terms_find_get"];
        /**
         * Find Term Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        put: operations["find_term_unsupported_method_delete_api_terms_find_put"];
        /**
         * Find Term Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        post: operations["find_term_unsupported_method_delete_api_terms_find_post"];
        /**
         * Find Term Unsupported Method Delete
         * @description Return 405 for unsupported DELETE method on /find endpoint.
         */
        delete: operations["find_term_unsupported_method_delete_api_terms_find_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Terms */
        get: operations["list_terms_api_terms__get"];
        put?: never;
        /** Create Term */
        post: operations["create_term_api_terms__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Term */
        get: operations["get_term_api_terms__id__get"];
        /** Update Term */
        put: operations["update_term_api_terms__id__put"];
        post?: never;
        /** Delete Term */
        delete: operations["delete_term_api_terms__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/term-relationships/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Relationships */
        get: operations["list_relationships_api_term_relationships__get"];
        put?: never;
        /** Create Relationship */
        post: operations["create_relationship_api_term_relationships__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/term-relationships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Relationship */
        get: operations["get_relationship_api_term_relationships__id__get"];
        /** Update Relationship */
        put: operations["update_relationship_api_term_relationships__id__put"];
        post?: never;
        /** Delete Relationship */
        delete: operations["delete_relationship_api_term_relationships__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DomainCreate */
        DomainCreate: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
        };
        /** DomainOut */
        DomainOut: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
        };
        /** DomainUpdate */
        DomainUpdate: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Layer Id */
            layer_id?: string | null;
        };
        /** FindDomainResult */
        FindDomainResult: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
            /** Score */
            score: number;
            /** Distance */
            distance: number;
        };
        /** FindLayerResult */
        FindLayerResult: {
            /** Title */
            title: string;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
            /** Score */
            score: number;
            /** Distance */
            distance: number;
        };
        /** FindTermResult */
        FindTermResult: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Parent Term Id */
            parent_term_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version: number;
            /** Last Modified */
            last_modified: string;
            /** Score */
            score: number;
            /** Distance */
            distance: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LayerCreate */
        LayerCreate: {
            /** Title */
            title: string;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
        };
        /** LayerOut */
        LayerOut: {
            /** Title */
            title: string;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
        };
        /** LayerUpdate */
        LayerUpdate: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
        };
        /** TermCreate */
        TermCreate: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Parent Term Id */
            parent_term_id?: string | null;
        };
        /** TermOut */
        TermOut: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Parent Term Id */
            parent_term_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version: number;
            /** Last Modified */
            last_modified: string;
        };
        /** TermRelationshipCreate */
        TermRelationshipCreate: {
            /**
             * Source Term Id
             * Format: uuid
             */
            source_term_id: string;
            /**
             * Target Term Id
             * Format: uuid
             */
            target_term_id: string;
            /** Predicate */
            predicate: string;
        };
        /** TermRelationshipOut */
        TermRelationshipOut: {
            /**
             * Source Term Id
             * Format: uuid
             */
            source_term_id: string;
            /**
             * Target Term Id
             * Format: uuid
             */
            target_term_id: string;
            /** Predicate */
            predicate: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at: string;
            /** Source Term */
            source_term?: {
                [key: string]: unknown;
            } | null;
            /** Target Term */
            target_term?: {
                [key: string]: unknown;
            } | null;
        };
        /** TermRelationshipUpdate */
        TermRelationshipUpdate: {
            /** Predicate */
            predicate: string;
        };
        /** TermUpdate */
        TermUpdate: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Parent Term Id */
            parent_term_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    find_layer_unsupported_method_delete_api_layers_find_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_layer_unsupported_method_delete_api_layers_find_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_layer_unsupported_method_delete_api_layers_find_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindLayerResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_layer_unsupported_method_delete_api_layers_find_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_layers_api_layers__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                sort?: string | null;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_layer_api_layers__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerCreate"];
            };
        };
        responses: {
            /** @description Layer created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_layer_api_layers__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Layer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_layer_api_layers__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Layer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_layer_api_layers__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Layer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_domain_unsupported_method_delete_api_domains_find_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_domain_unsupported_method_delete_api_domains_find_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_domain_unsupported_method_delete_api_domains_find_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindDomainResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_domain_unsupported_method_delete_api_domains_find_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_domains_api_domains__get: {
        parameters: {
            query?: {
                layer_id?: string;
                skip?: number;
                limit?: number;
                sort?: string | null;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_domain_api_domains__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_api_domains__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_domain_api_domains__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_domain_api_domains__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_term_unsupported_method_delete_api_terms_find_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_term_unsupported_method_delete_api_terms_find_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_term_unsupported_method_delete_api_terms_find_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindTermResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    find_term_unsupported_method_delete_api_terms_find_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_terms_api_terms__get: {
        parameters: {
            query?: {
                domain_id?: string;
                layer_id?: string;
                parent_term_id?: string;
                skip?: number;
                limit?: number;
                sort?: string | null;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_term_api_terms__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_term_api_terms__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Term not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_term_api_terms__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_term_api_terms__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationships_api_term_relationships__get: {
        parameters: {
            query?: {
                source_term_id?: string;
                target_term_id?: string;
                predicate?: string;
                skip?: number;
                limit?: number;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relationship_api_term_relationships__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermRelationshipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relationship_api_term_relationships__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_relationship_api_term_relationships__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermRelationshipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relationship_api_term_relationships__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
