/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/layers/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find Layer */
        post: operations["find_layer_api_layers_find_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Layers */
        get: operations["list_layers_api_layers__get"];
        put?: never;
        /** Create Layer */
        post: operations["create_layer_api_layers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Layer */
        get: operations["get_layer_api_layers__id__get"];
        /** Update Layer */
        put: operations["update_layer_api_layers__id__put"];
        post?: never;
        /** Delete Layer */
        delete: operations["delete_layer_api_layers__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find Domain */
        post: operations["find_domain_api_domains_find_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Domains */
        get: operations["list_domains_api_domains__get"];
        put?: never;
        /** Create Domain */
        post: operations["create_domain_api_domains__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Domain */
        get: operations["get_domain_api_domains__id__get"];
        /** Update Domain */
        put: operations["update_domain_api_domains__id__put"];
        post?: never;
        /** Delete Domain */
        delete: operations["delete_domain_api_domains__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/find": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Find Term */
        post: operations["find_term_api_terms_find_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Terms */
        get: operations["list_terms_api_terms__get"];
        put?: never;
        /** Create Term */
        post: operations["create_term_api_terms__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Term */
        get: operations["get_term_api_terms__id__get"];
        /** Update Term */
        put: operations["update_term_api_terms__id__put"];
        post?: never;
        /** Delete Term */
        delete: operations["delete_term_api_terms__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/term-relationships/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Relationships */
        get: operations["list_relationships_api_term_relationships__get"];
        put?: never;
        /** Create Relationship */
        post: operations["create_relationship_api_term_relationships__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/term-relationships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Relationship */
        get: operations["get_relationship_api_term_relationships__id__get"];
        /** Update Relationship */
        put: operations["update_relationship_api_term_relationships__id__put"];
        post?: never;
        /** Delete Relationship */
        delete: operations["delete_relationship_api_term_relationships__id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph Stats
         * @description Get comprehensive graph statistics from both SPARQL and NetworkX services.
         */
        get: operations["get_graph_stats_api_graph_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Graphs
         * @description Refresh both SPARQL and NetworkX graphs from the database.
         */
        post: operations["refresh_graphs_api_graph_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/sparql/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Sparql Query
         * @description Execute a SPARQL query against the RDF graph.
         */
        post: operations["execute_sparql_query_api_graph_sparql_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/sparql/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Rdf
         * @description Export the RDF graph in various formats.
         */
        get: operations["export_rdf_api_graph_sparql_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/search/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Terms
         * @description Search for terms by title using SPARQL.
         */
        get: operations["search_terms_api_graph_search_terms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/search/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search And Analyze
         * @description Search for terms and provide comprehensive analysis.
         */
        post: operations["search_and_analyze_api_graph_search_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/analytics/centrality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Centrality
         * @description Calculate node centrality using NetworkX algorithms.
         */
        post: operations["calculate_centrality_api_graph_analytics_centrality_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/analytics/communities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detect Communities
         * @description Detect communities in the graph using NetworkX algorithms.
         */
        get: operations["detect_communities_api_graph_analytics_communities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/path/shortest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Find Shortest Path
         * @description Find the shortest path between two nodes.
         */
        post: operations["find_shortest_path_api_graph_path_shortest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Neighbors
         * @description Get neighbors of a node at specified depth.
         */
        post: operations["get_neighbors_api_graph_neighbors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/terms/{term_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Related Terms
         * @description Find related terms using both SPARQL and NetworkX for comprehensive results.
         */
        get: operations["find_related_terms_api_graph_terms__term_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/terms/{term_id}/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Term Hierarchy
         * @description Get the full hierarchy for a term (ancestors and descendants).
         */
        get: operations["get_term_hierarchy_api_graph_terms__term_id__hierarchy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/terms/{term_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Term Info
         * @description Get detailed information about a specific term.
         */
        get: operations["get_term_info_api_graph_terms__term_id__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/domains/{domain_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analyze Domain
         * @description Comprehensive analysis of a domain's structure.
         */
        get: operations["analyze_domain_api_graph_domains__domain_id__analyze_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/domains/hierarchy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Domain Hierarchy
         * @description Get the domain hierarchy for a layer or all layers.
         */
        get: operations["get_domain_hierarchy_api_graph_domains_hierarchy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/layers/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layer Analytics
         * @description Get comprehensive analytics for a layer or all layers.
         */
        get: operations["get_layer_analytics_api_graph_layers_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/layers/{layer_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Layer Info
         * @description Get detailed information about a specific layer.
         */
        get: operations["get_layer_info_api_graph_layers__layer_id__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/domains/{domain_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Domain Info
         * @description Get detailed information about a specific domain.
         */
        get: operations["get_domain_info_api_graph_domains__domain_id__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Graph Data
         * @description Export comprehensive graph data in various formats.
         */
        get: operations["export_graph_data_api_graph_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/examples/sparql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sparql Examples
         * @description Get example SPARQL queries for the Context Studio graph.
         */
        get: operations["get_sparql_examples_api_graph_examples_sparql_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CentralityRequest */
        CentralityRequest: {
            /**
             * Method
             * @default pagerank
             */
            method: string | null;
        };
        /** DomainCreate */
        DomainCreate: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
        };
        /** DomainOut */
        DomainOut: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
        };
        /** DomainUpdate */
        DomainUpdate: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Layer Id */
            layer_id?: string | null;
        };
        /** FindDomainRequest */
        FindDomainRequest: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Layer Id */
            layer_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Minimum Score
             * @default 0.1
             */
            minimum_score: number | null;
            /**
             * Limit
             * @default 1
             */
            limit: number | null;
        };
        /** FindDomainResult */
        FindDomainResult: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
            /** Score */
            score: number;
            /** Distance */
            distance: number;
        };
        /** FindLayerRequest */
        FindLayerRequest: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Minimum Score
             * @default 0.1
             */
            minimum_score: number | null;
            /**
             * Limit
             * @default 1
             */
            limit: number | null;
        };
        /** FindLayerResult */
        FindLayerResult: {
            /** Title */
            title: string;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
            /** Score */
            score: number;
            /** Distance */
            distance: number;
        };
        /** FindTermRequest */
        FindTermRequest: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Layer Id */
            layer_id?: string | null;
            /** Domain Id */
            domain_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Minimum Score
             * @default 0.1
             */
            minimum_score: number | null;
            /**
             * Limit
             * @default 1
             */
            limit: number | null;
        };
        /** FindTermResult */
        FindTermResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Parent Term Id */
            parent_term_id?: string | null;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version: number;
            /** Last Modified */
            last_modified: string;
            /** Score */
            score: number;
            /** Distance */
            distance: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LayerCreate */
        LayerCreate: {
            /** Title */
            title: string;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
        };
        /** LayerOut */
        LayerOut: {
            /** Title */
            title: string;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version?: number | null;
            /** Last Modified */
            last_modified?: string | null;
        };
        /** LayerUpdate */
        LayerUpdate: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Primary Predicate */
            primary_predicate?: string | null;
        };
        /** NeighborsRequest */
        NeighborsRequest: {
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Type
             * @default term
             */
            entity_type: string | null;
            /**
             * Depth
             * @default 1
             */
            depth: number | null;
            /**
             * Direction
             * @default both
             */
            direction: string | null;
        };
        /** PaginatedDomainsResponse */
        PaginatedDomainsResponse: {
            /** Data */
            data: components["schemas"]["DomainOut"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /** PaginatedLayersResponse */
        PaginatedLayersResponse: {
            /** Data */
            data: components["schemas"]["LayerOut"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /** PaginatedTermsResponse */
        PaginatedTermsResponse: {
            /** Data */
            data: components["schemas"]["TermOut"][];
            /** Total */
            total: number;
            /** Skip */
            skip: number;
            /** Limit */
            limit: number;
        };
        /** PathRequest */
        PathRequest: {
            /** Source Id */
            source_id: string;
            /** Target Id */
            target_id: string;
            /**
             * Source Type
             * @default term
             */
            source_type: string | null;
            /**
             * Target Type
             * @default term
             */
            target_type: string | null;
        };
        /** SPARQLQuery */
        SPARQLQuery: {
            /** Query */
            query: string;
            /**
             * Format
             * @default json
             */
            format: string | null;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Term */
            term: string;
            /**
             * Exact
             * @default false
             */
            exact: boolean | null;
            /**
             * Analysis Depth
             * @default 1
             */
            analysis_depth: number | null;
        };
        /** TermCreate */
        TermCreate: {
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Parent Term Id */
            parent_term_id?: string | null;
        };
        /** TermOut */
        TermOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Definition */
            definition: string;
            /**
             * Domain Id
             * Format: uuid
             */
            domain_id: string;
            /**
             * Layer Id
             * Format: uuid
             */
            layer_id: string;
            /** Parent Term Id */
            parent_term_id?: string | null;
            /** Title Embedding */
            title_embedding?: number[] | null;
            /** Definition Embedding */
            definition_embedding?: number[] | null;
            /** Created At */
            created_at: string;
            /** Version */
            version: number;
            /** Last Modified */
            last_modified: string;
        };
        /** TermRelationshipCreate */
        TermRelationshipCreate: {
            /**
             * Source Term Id
             * Format: uuid
             */
            source_term_id: string;
            /**
             * Target Term Id
             * Format: uuid
             */
            target_term_id: string;
            /** Predicate */
            predicate: string;
        };
        /** TermRelationshipOut */
        TermRelationshipOut: {
            /**
             * Source Term Id
             * Format: uuid
             */
            source_term_id: string;
            /**
             * Target Term Id
             * Format: uuid
             */
            target_term_id: string;
            /** Predicate */
            predicate: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at: string;
            /** Source Term */
            source_term?: {
                [key: string]: unknown;
            } | null;
            /** Target Term */
            target_term?: {
                [key: string]: unknown;
            } | null;
        };
        /** TermRelationshipUpdate */
        TermRelationshipUpdate: {
            /** Predicate */
            predicate: string;
        };
        /** TermUpdate */
        TermUpdate: {
            /** Title */
            title?: string | null;
            /** Definition */
            definition?: string | null;
            /** Parent Term Id */
            parent_term_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    find_layer_api_layers_find_post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindLayerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindLayerResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_layers_api_layers__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                sortBy?: string;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLayersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_layer_api_layers__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerCreate"];
            };
        };
        responses: {
            /** @description Layer created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_layer_api_layers__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Layer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_layer_api_layers__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerOut"];
                };
            };
            /** @description Layer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_layer_api_layers__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Layer not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_domain_api_domains_find_post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindDomainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindDomainResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_domains_api_domains__get: {
        parameters: {
            query?: {
                layer_id?: string;
                skip?: number;
                limit?: number;
                sortBy?: string;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDomainsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_domain_api_domains__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_api_domains__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_domain_api_domains__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DomainUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainOut"];
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_domain_api_domains__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Domain not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_term_api_terms_find_post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FindTermRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindTermResult"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_terms_api_terms__get: {
        parameters: {
            query?: {
                domain_id?: string;
                layer_id?: string;
                parent_term_id?: string;
                skip?: number;
                limit?: number;
                sortBy?: string;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_term_api_terms__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_term_api_terms__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Term not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_term_api_terms__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_term_api_terms__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationships_api_term_relationships__get: {
        parameters: {
            query?: {
                source_term_id?: string;
                target_term_id?: string;
                predicate?: string;
                skip?: number;
                limit?: number;
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relationship_api_term_relationships__post: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermRelationshipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relationship_api_term_relationships__id__get: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_relationship_api_term_relationships__id__put: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermRelationshipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermRelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relationship_api_term_relationships__id__delete: {
        parameters: {
            query?: {
                SessionLocal?: unknown;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_stats_api_graph_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    refresh_graphs_api_graph_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    execute_sparql_query_api_graph_sparql_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SPARQLQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_rdf_api_graph_sparql_export_get: {
        parameters: {
            query?: {
                /** @description RDF serialization format */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_terms_api_graph_search_terms_get: {
        parameters: {
            query: {
                /** @description Term title to search for */
                title: string;
                /** @description Whether to do exact match */
                exact?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_and_analyze_api_graph_search_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_centrality_api_graph_analytics_centrality_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CentralityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_communities_api_graph_analytics_communities_get: {
        parameters: {
            query?: {
                /** @description Community detection method */
                method?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_shortest_path_api_graph_path_shortest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neighbors_api_graph_neighbors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NeighborsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_related_terms_api_graph_terms__term_id__related_get: {
        parameters: {
            query?: {
                /** @description Maximum depth of relationships to traverse */
                max_depth?: number;
            };
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_term_hierarchy_api_graph_terms__term_id__hierarchy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_term_info_api_graph_terms__term_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_domain_api_graph_domains__domain_id__analyze_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_hierarchy_api_graph_domains_hierarchy_get: {
        parameters: {
            query?: {
                /** @description Optional layer ID to filter by */
                layer_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_analytics_api_graph_layers_analytics_get: {
        parameters: {
            query?: {
                /** @description Optional layer ID to analyze */
                layer_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_layer_info_api_graph_layers__layer_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_domain_info_api_graph_domains__domain_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_graph_data_api_graph_export_get: {
        parameters: {
            query?: {
                /** @description Export format (json, turtle, graphml) */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sparql_examples_api_graph_examples_sparql_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
