"""Add PipelineRun joined-table base and per-type subclasses

Revision ID: 01e4a27284f4
Revises: b6ef19628578
Create Date: 2026-05-22 22:17:23.848413

This migration introduces:
- pipeline_runs: joined-table base extending batch_runs
- individual_extraction_runs: migrated from extraction_runs (Wave A)
- schema_extraction_runs, schema_node_grounding_runs, schema_node_definition_refinement_runs,
  schema_node_connection_refinement_runs: per-type subclasses (stubs for Phase 4B.1)

Note: The CHECK constraint on batch_runs.run_type needs to be updated to include 'pipeline'.
This is deferred to a separate migration due to SQLite constraint alteration limitations.
For now, the constraint is updated in the SQLAlchemy model; new inserts will validate
via the ORM, and the database constraint is loosened by the next migration.

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01e4a27284f4"
down_revision = "b6ef19628578"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pipeline_type", sa.String(length=50), nullable=False),
        sa.Column("implementation_id", sa.String(length=100), nullable=False),
        sa.Column("configuration_ref", sa.String(length=255), nullable=False),
        sa.Column("input_summary", sa.JSON(), nullable=False),
        sa.Column("output_summary", sa.JSON(), nullable=False),
        sa.Column("llm_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["batch_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_pipeline_impl_id", "pipeline_runs", ["implementation_id"], unique=False
    )
    op.create_table(
        "individual_extraction_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_text_hash", sa.String(length=64), nullable=False),
        sa.Column("source_document_uri", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schema_extraction_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schema_node_connection_refinement_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schema_node_definition_refinement_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schema_node_grounding_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schema_node_grounding_runs")
    op.drop_table("schema_node_definition_refinement_runs")
    op.drop_table("schema_node_connection_refinement_runs")
    op.drop_table("schema_extraction_runs")
    op.drop_table("individual_extraction_runs")
    op.drop_index("idx_pipeline_impl_id", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
