"""Add status column to ontology_entities

Revision ID: 30974cfce846
Revises: dea59f0b2b28
Create Date: 2026-05-09 13:28:48.292101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30974cfce846'
down_revision = 'dea59f0b2b28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ontology_entities', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    op.create_index(op.f('ix_ontology_entities_status'), 'ontology_entities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontology_entities_status'), table_name='ontology_entities')
    op.drop_column('ontology_entities', 'status')
    # ### end Alembic commands ###
