"""Add AttributeDefinition table with class_id FK and unique constraint

Revision ID: 5acc1ebd83f7
Revises: cf3a1808ba8d
Create Date: 2026-08-31 12:09:08.568713

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5acc1ebd83f7'
down_revision = 'cf3a1808ba8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('datatype', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('external_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_run_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['ontology_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'identifier', name='uk_attribute_class_identifier')
    )
    op.create_index('idx_class_id_sort_order', 'attribute_definitions', ['class_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_attribute_definitions_class_id'), 'attribute_definitions', ['class_id'], unique=False)
    op.create_index(op.f('ix_attribute_definitions_source_run_id'), 'attribute_definitions', ['source_run_id'], unique=False)
    op.create_index(op.f('ix_attribute_definitions_status'), 'attribute_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_attribute_definitions_title'), 'attribute_definitions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribute_definitions_title'), table_name='attribute_definitions')
    op.drop_index(op.f('ix_attribute_definitions_status'), table_name='attribute_definitions')
    op.drop_index(op.f('ix_attribute_definitions_source_run_id'), table_name='attribute_definitions')
    op.drop_index(op.f('ix_attribute_definitions_class_id'), table_name='attribute_definitions')
    op.drop_index('idx_class_id_sort_order', table_name='attribute_definitions')
    op.drop_table('attribute_definitions')
    # ### end Alembic commands ###
