"""initial ontology schema with entities relationships and change events

Revision ID: 5cf2ea2adf3c
Revises: 
Create Date: 2026-03-27 00:45:21.794172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf2ea2adf3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('property_definition_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_id != target_id', name='check_no_self_loop'),
    sa.ForeignKeyConstraint(['property_definition_id'], ['ontology_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['ontology_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['ontology_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'property_definition_id', name='uk_relationship_triple')
    )
    op.create_index(op.f('ix_relationships_property_definition_id'), 'relationships', ['property_definition_id'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.drop_index(op.f('idx_changeset_id'), table_name='change_events')
    op.drop_index(op.f('idx_entity_id'), table_name='change_events')
    op.drop_index(op.f('idx_operation'), table_name='change_events')
    op.drop_index(op.f('idx_concept_scheme_id'), table_name='ontology_entities')
    op.drop_index(op.f('idx_created_at'), table_name='ontology_entities')
    op.drop_index(op.f('idx_parent_class_id'), table_name='ontology_entities')
    op.drop_index(op.f('idx_taxonomy_id'), table_name='ontology_entities')
    op.create_index(op.f('ix_property_definitions_identifier'), 'property_definitions', ['identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_definitions_identifier'), table_name='property_definitions')
    op.create_index(op.f('idx_taxonomy_id'), 'ontology_entities', ['taxonomy_id'], unique=False)
    op.create_index(op.f('idx_parent_class_id'), 'ontology_entities', ['parent_class_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'ontology_entities', ['created_at'], unique=False)
    op.create_index(op.f('idx_concept_scheme_id'), 'ontology_entities', ['concept_scheme_id'], unique=False)
    op.create_index(op.f('idx_operation'), 'change_events', ['operation'], unique=False)
    op.create_index(op.f('idx_entity_id'), 'change_events', ['entity_id'], unique=False)
    op.create_index(op.f('idx_changeset_id'), 'change_events', ['changeset_id'], unique=False)
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_property_definition_id'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
