"""Add batch_runs base table and migrate change_events to use batch_run_id

Revision ID: 7609a5828f1b
Revises: 441832e0bb55
Create Date: 2026-05-08 12:32:30.166529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '7609a5828f1b'
down_revision = '441832e0bb55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create batch_runs base table
    op.create_table('batch_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('affected_entity_ids', sa.JSON(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("run_type IN ('import', 'extraction')", name='check_valid_run_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_type_status', 'batch_runs', ['run_type', 'status'], unique=False)
    op.create_index(op.f('ix_batch_runs_created_at'), 'batch_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_batch_runs_run_type'), 'batch_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_batch_runs_status'), 'batch_runs', ['status'], unique=False)

    # Step 2: Migrate data from import_runs to batch_runs with integrity verification
    # First, count existing import_runs for validation
    count_result = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM import_runs"))
    import_run_count = count_result.scalar()

    insert_result = op.get_bind().execute(sa.text("""
        INSERT INTO batch_runs (id, created_at, created_by, status, affected_entity_ids, run_type)
        SELECT id, created_at, created_by, status, affected_entity_ids, 'import' as run_type
        FROM import_runs
    """))

    # Verify all import_runs were migrated
    if insert_result.rowcount != import_run_count:
        raise Exception(
            f"Data migration integrity error: expected to insert {import_run_count} rows, "
            f"but inserted {insert_result.rowcount}"
        )

    # Step 3: Create extraction_runs table
    op.create_table('extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_uri', sa.Text(), nullable=True),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False),
    sa.Column('pipeline_config_ref', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('triples_extracted', sa.Integer(), nullable=False),
    sa.Column('triples_committed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['batch_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Step 4-6: Update change_events to use batch_run_id
    # First, add the new column and copy data over
    op.add_column('change_events', sa.Column('batch_run_id', sa.String(length=36), nullable=True))

    # Count change_events that have import_run_id before migration
    events_with_import_run = op.get_bind().execute(
        sa.text("SELECT COUNT(*) FROM change_events WHERE import_run_id IS NOT NULL")
    ).scalar()

    # Migrate data from import_run_id to batch_run_id with integrity verification
    update_result = op.get_bind().execute(sa.text("""
        UPDATE change_events SET batch_run_id = import_run_id WHERE import_run_id IS NOT NULL
    """))

    if update_result.rowcount != events_with_import_run:
        raise Exception(
            f"Data migration integrity error: expected to update {events_with_import_run} rows, "
            f"but updated {update_result.rowcount}"
        )

    # Now use batch mode to drop the old column and update constraints
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index('idx_import_run_id')
        batch_op.create_index('ix_change_events_batch_run_id', ['batch_run_id'], unique=False)
        batch_op.drop_constraint('fk_change_events_import_run_id', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_change_events_batch_run_id',
            'batch_runs',
            ['batch_run_id'],
            ['id'],
            ondelete='SET NULL'
        )
        batch_op.drop_column('import_run_id')

    # Step 7: Update import_runs to be a joined-table subclass
    # SQLite requires batch mode for structural changes
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_import_runs_batch_runs_id',
            'batch_runs',
            ['id'],
            ['id'],
            ondelete='CASCADE'
        )
        batch_op.drop_column('affected_entity_ids')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse steps in reverse order

    # Restore import_runs columns with batch mode
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.VARCHAR(length=36), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('affected_entity_ids', sqlite.JSON(), nullable=False))
        batch_op.drop_constraint('fk_import_runs_batch_runs_id', type_='foreignkey')

    # Migrate data back to import_runs (restore from batch_runs)
    op.get_bind().execute(sa.text("""
        UPDATE import_runs SET created_at = (SELECT created_at FROM batch_runs WHERE batch_runs.id = import_runs.id)
        WHERE EXISTS (SELECT 1 FROM batch_runs WHERE batch_runs.id = import_runs.id)
    """))
    op.get_bind().execute(sa.text("""
        UPDATE import_runs SET created_by = (SELECT created_by FROM batch_runs WHERE batch_runs.id = import_runs.id)
        WHERE EXISTS (SELECT 1 FROM batch_runs WHERE batch_runs.id = import_runs.id)
    """))
    op.get_bind().execute(sa.text("""
        UPDATE import_runs SET status = (SELECT status FROM batch_runs WHERE batch_runs.id = import_runs.id)
        WHERE EXISTS (SELECT 1 FROM batch_runs WHERE batch_runs.id = import_runs.id)
    """))
    op.get_bind().execute(sa.text("""
        UPDATE import_runs SET affected_entity_ids = (SELECT affected_entity_ids FROM batch_runs WHERE batch_runs.id = import_runs.id)
        WHERE EXISTS (SELECT 1 FROM batch_runs WHERE batch_runs.id = import_runs.id)
    """))

    # Restore change_events columns with batch mode
    # Step 1: Add import_run_id column back
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_run_id', sa.VARCHAR(length=36), nullable=True))

    # Step 2: Copy data back from batch_run_id to import_run_id while both columns exist
    op.get_bind().execute(sa.text("""
        UPDATE change_events SET import_run_id = batch_run_id WHERE batch_run_id IS NOT NULL
    """))

    # Step 3: Drop batch_run_id and restore indexes/constraints
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index('ix_change_events_batch_run_id')
        batch_op.create_index('idx_import_run_id', ['import_run_id'], unique=False)
        batch_op.drop_constraint('fk_change_events_batch_run_id', type_='foreignkey')
        batch_op.create_foreign_key(
            'fk_change_events_import_run_id',
            'import_runs',
            ['import_run_id'],
            ['id'],
            ondelete='SET NULL'
        )
        batch_op.drop_column('batch_run_id')

    # Drop extraction_runs and batch_runs
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_batch_runs_status'), table_name='batch_runs')
    op.drop_index(op.f('ix_batch_runs_run_type'), table_name='batch_runs')
    op.drop_index(op.f('ix_batch_runs_created_at'), table_name='batch_runs')
    op.drop_index('idx_run_type_status', table_name='batch_runs')
    op.drop_table('batch_runs')
    # ### end Alembic commands ###
