"""Add versioning and collaboration tables

Revision ID: a1fd835be0a1
Revises: 3c8f2e9a1b5c
Create Date: 2026-04-05 02:30:00.000000

"""

import sqlalchemy as sa
from alembic import op

# ### commands auto generated by Alembic - please adjust! ###

# revision identifiers, used by Alembic.
revision = "a1fd835be0a1"
down_revision = "3c8f2e9a1b5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "change_events",
        sa.Column("processed", sa.Boolean(), nullable=False, server_default="0"),
    )
    op.create_index("idx_processed", "change_events", ["processed"], unique=False)
    op.create_table(
        "entity_versions",
        sa.Column("entity_id", sa.String(36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(20), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("entity_id", "version", name="pk_entity_versions"),
    )
    op.create_table(
        "changesets",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("state", sa.String(20), nullable=False, server_default="working"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.PrimaryKeyConstraint("id", name="pk_changesets"),
    )
    op.create_table(
        "changeset_events",
        sa.Column("changeset_id", sa.String(36), nullable=False),
        sa.Column("change_event_id", sa.String(36), nullable=False),
        sa.ForeignKeyConstraint(
            ["changeset_id"], ["changesets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["change_event_id"], ["change_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "changeset_id", "change_event_id", name="pk_changeset_events"
        ),
    )
    op.create_index(
        "ix_changeset_events_changeset_id", "changeset_events", ["changeset_id"]
    )
    op.create_index(
        "ix_changeset_events_change_event_id", "changeset_events", ["change_event_id"]
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("changeset_id", sa.String(36), nullable=False),
        sa.Column("state", sa.String(20), nullable=False, server_default="open"),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["changeset_id"], ["changesets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_proposals"),
    )
    op.create_index("ix_proposals_changeset_id", "proposals", ["changeset_id"])
    op.create_table(
        "conflict_resolutions",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("proposal_id", sa.String(36), nullable=False),
        sa.Column("entity_id", sa.String(36), nullable=False),
        sa.Column("field_name", sa.String(255), nullable=False),
        sa.Column("resolved_value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["proposal_id"], ["proposals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="pk_conflict_resolutions"),
    )
    op.create_index("ix_proposal_id", "conflict_resolutions", ["proposal_id"])
    op.create_index("ix_entity_id", "conflict_resolutions", ["entity_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entity_id", table_name="conflict_resolutions")
    op.drop_index("ix_proposal_id", table_name="conflict_resolutions")
    op.drop_table("conflict_resolutions")
    op.drop_index("ix_proposals_changeset_id", table_name="proposals")
    op.drop_table("proposals")
    op.drop_index("ix_changeset_events_change_event_id", table_name="changeset_events")
    op.drop_index("ix_changeset_events_changeset_id", table_name="changeset_events")
    op.drop_table("changeset_events")
    op.drop_table("changesets")
    op.drop_table("entity_versions")
    op.drop_index("idx_processed", table_name="change_events")
    op.drop_column("change_events", "processed")
    # ### end Alembic commands ###
