"""Add multi-class support for Individual entities with ordered inheritance

Revision ID: b2ac4e5f3d7a
Revises: a1fd835be0a1
Create Date: 2026-05-01 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# ### commands auto generated by Alembic - please adjust! ###

# revision identifiers, used by Alembic.
revision = "b2ac4e5f3d7a"
down_revision = "a1fd835be0a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create individual_classes join table for ordered multi-class membership
    op.create_table(
        "individual_classes",
        sa.Column("individual_id", sa.String(36), nullable=False),
        sa.Column("class_id", sa.String(36), nullable=False),
        sa.Column(
            "position",
            sa.Integer(),
            nullable=False,
            doc="Zero-based position in ordered list",
        ),
        sa.ForeignKeyConstraint(
            ["individual_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["class_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "individual_id", "class_id", name="pk_individual_classes"
        ),
        sa.UniqueConstraint("individual_id", "position", name="uk_individual_position"),
    )
    op.create_index("idx_class_id", "individual_classes", ["class_id"], unique=False)

    # Migrate existing single-class data from ontology_entities.class_id to individual_classes
    # Each existing Individual.class_id becomes the first (position 0) entry
    migration_sql = """
    INSERT INTO individual_classes (individual_id, class_id, position)
    SELECT id, class_id, 0
    FROM ontology_entities
    WHERE node_type = 'individual' AND class_id IS NOT NULL
    """
    op.execute(migration_sql)


def downgrade() -> None:
    # Drop the individual_classes table
    op.drop_index("idx_class_id", "individual_classes")
    op.drop_table("individual_classes")
