"""Remove duplicate index on is_active column in datasets table

Revision ID: b6ef19628578
Revises: 50c585494888
Create Date: 2026-05-14 11:10:10.323951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ef19628578'
down_revision = '50c585494888'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_is_active'), table_name='datasets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_is_active'), 'datasets', ['is_active'], unique=False)
    # ### end Alembic commands ###
