"""initial ontology schema with all entities

Revision ID: da604771ce10
Revises:
Create Date: 2026-03-27 01:01:28.938000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "da604771ce10"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ontology_entities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("node_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("taxonomy_id", sa.String(length=36), nullable=True),
        sa.Column("concept_scheme_id", sa.String(length=36), nullable=True),
        sa.Column("class_id", sa.String(length=36), nullable=True),
        sa.Column("parent_class_id", sa.String(length=36), nullable=True),
        sa.Column("structural_property_id", sa.String(length=36), nullable=True),
        sa.Column("external_references", sa.JSON(), nullable=False),
        sa.Column("lexical_senses", sa.JSON(), nullable=False),
        sa.Column("data_properties", sa.JSON(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("is_indexed", sa.Boolean(), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=True),
        sa.Column("ontology_mapping", sa.JSON(), nullable=True),
        sa.Column("is_relevant", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "node_type IN ('taxonomy', 'concept_scheme', 'class', 'individual', 'property_definition')",
            name="check_valid_node_type",
        ),
        sa.ForeignKeyConstraint(
            ["class_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["concept_scheme_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_class_id"], ["ontology_entities.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["structural_property_id"], ["ontology_entities.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["taxonomy_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_index(
        "idx_node_type_title", "ontology_entities", ["node_type", "title"], unique=False
    )
    op.create_index(
        op.f("ix_ontology_entities_concept_scheme_id"),
        "ontology_entities",
        ["concept_scheme_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ontology_entities_node_type"),
        "ontology_entities",
        ["node_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ontology_entities_parent_class_id"),
        "ontology_entities",
        ["parent_class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ontology_entities_taxonomy_id"),
        "ontology_entities",
        ["taxonomy_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ontology_entities_title"), "ontology_entities", ["title"], unique=False
    )
    op.create_table(
        "change_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column("previous_state", sa.JSON(), nullable=True),
        sa.Column("new_state", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("changeset_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_entity_id_timestamp",
        "change_events",
        ["entity_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_events_changeset_id"),
        "change_events",
        ["changeset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_change_events_entity_id"), "change_events", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_change_events_operation"), "change_events", ["operation"], unique=False
    )
    op.create_index(
        op.f("ix_change_events_timestamp"), "change_events", ["timestamp"], unique=False
    )
    op.create_table(
        "property_definitions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("identifier", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ontology_mapping", sa.JSON(), nullable=True),
        sa.Column("is_relevant", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["ontology_entities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_property_definitions_identifier"),
        "property_definitions",
        ["identifier"],
        unique=True,
    )
    op.create_table(
        "relationships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("property_definition_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source_id != target_id", name="check_no_self_loop"),
        sa.ForeignKeyConstraint(
            ["property_definition_id"], ["ontology_entities.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["ontology_entities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_id",
            "target_id",
            "property_definition_id",
            name="uk_relationship_triple",
        ),
    )
    op.create_index(
        op.f("ix_relationships_property_definition_id"),
        "relationships",
        ["property_definition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_relationships_source_id"), "relationships", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_relationships_target_id"), "relationships", ["target_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_relationships_target_id"), table_name="relationships")
    op.drop_index(op.f("ix_relationships_source_id"), table_name="relationships")
    op.drop_index(
        op.f("ix_relationships_property_definition_id"), table_name="relationships"
    )
    op.drop_table("relationships")
    op.drop_index(
        op.f("ix_property_definitions_identifier"), table_name="property_definitions"
    )
    op.drop_table("property_definitions")
    op.drop_index(op.f("ix_change_events_timestamp"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_operation"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_entity_id"), table_name="change_events")
    op.drop_index(op.f("ix_change_events_changeset_id"), table_name="change_events")
    op.drop_index("idx_entity_id_timestamp", table_name="change_events")
    op.drop_table("change_events")
    op.drop_index(op.f("ix_ontology_entities_title"), table_name="ontology_entities")
    op.drop_index(
        op.f("ix_ontology_entities_taxonomy_id"), table_name="ontology_entities"
    )
    op.drop_index(
        op.f("ix_ontology_entities_parent_class_id"), table_name="ontology_entities"
    )
    op.drop_index(
        op.f("ix_ontology_entities_node_type"), table_name="ontology_entities"
    )
    op.drop_index(
        op.f("ix_ontology_entities_concept_scheme_id"), table_name="ontology_entities"
    )
    op.drop_index("idx_node_type_title", table_name="ontology_entities")
    op.drop_table("ontology_entities")
    # ### end Alembic commands ###
