apm.exporterconfig.file-log-exporter:
  id: 18e2426a-3d38-4dc0-970f-bb7abe2b9dfd
  path: apm.exporterconfig.file-log-exporter
  spec_node_id: apm.exporterconfig
  type: exporterconfig
  layer_id: apm
  name: File Log Exporter
  description: Log exporter writing structured logs to logs/context_studio.log
    file with rotation (loguru)
  attributes:
    type: logging
    endpoint: ./logs/context_studio.log
    enabled: true
  source_reference:
    provenance: extracted
    locations:
      - file: utils/logger.py
  metadata:
    created_at: 2026-03-23T12:34:47.329Z
    updated_at: 2026-03-23T12:34:47.329Z
    version: 1
