[pytest]
log_cli = true
log_cli_level = INFO
markers =
    integration: marks tests as integration tests
    performance: marks tests as performance tests
    slow: marks tests as slow-running tests
filterwarnings =
    ignore::DeprecationWarning:click.parser
    ignore::DeprecationWarning:spacy.cli._util
    ignore::DeprecationWarning:weasel.util.config
    ignore:Importing 'parser.split_arg_string' is deprecated:DeprecationWarning
    ignore:.*split_arg_string.*:DeprecationWarning
