[pytest]
log_cli = true
log_cli_level = INFO
filterwarnings =
    ignore::DeprecationWarning:click.parser
    ignore::DeprecationWarning:spacy.cli._util
    ignore::DeprecationWarning:weasel.util.config
    ignore:Importing 'parser.split_arg_string' is deprecated:DeprecationWarning
    ignore:.*split_arg_string.*:DeprecationWarning
