/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTaxonomiesRouteImport } from './routes/app/taxonomies'
import { Route as AppRelationshipsRouteImport } from './routes/app/relationships'
import { Route as AppPropertiesRouteImport } from './routes/app/properties'
import { Route as AppIndividualsRouteImport } from './routes/app/individuals'
import { Route as AppDatasetsRouteImport } from './routes/app/datasets'
import { Route as AppConfigRouteImport } from './routes/app/config'
import { Route as AppConceptSchemesRouteImport } from './routes/app/concept-schemes'
import { Route as AppClassesRouteImport } from './routes/app/classes'
import { Route as AppTaxonomiesIndexRouteImport } from './routes/app/taxonomies.index'
import { Route as AppReferenceIndexRouteImport } from './routes/app/reference/index'
import { Route as AppIndividualsIndexRouteImport } from './routes/app/individuals.index'
import { Route as AppConfigIndexRouteImport } from './routes/app/config/index'
import { Route as AppConceptSchemesIndexRouteImport } from './routes/app/concept-schemes.index'
import { Route as AppClassesIndexRouteImport } from './routes/app/classes.index'
import { Route as AppTaxonomiesTaxonomyIdRouteImport } from './routes/app/taxonomies.$taxonomyId'
import { Route as AppReferenceSearchRouteImport } from './routes/app/reference/search'
import { Route as AppReferenceRagTestRouteImport } from './routes/app/reference/rag-test'
import { Route as AppReferencePropertiesRouteImport } from './routes/app/reference/properties'
import { Route as AppRagTestRunnerRouteImport } from './routes/app/rag/test-runner'
import { Route as AppRagPipelineComparisonRouteImport } from './routes/app/rag/pipeline-comparison'
import { Route as AppRagExperimentsRouteImport } from './routes/app/rag/experiments'
import { Route as AppMonitoringTaskManagerRouteImport } from './routes/app/monitoring/task-manager'
import { Route as AppMonitoringSystemHealthRouteImport } from './routes/app/monitoring/system-health'
import { Route as AppMonitoringPerformanceRouteImport } from './routes/app/monitoring/performance'
import { Route as AppMonitoringLlmTraceabilityRouteImport } from './routes/app/monitoring/llm-traceability'
import { Route as AppMonitoringAnalyticsRouteImport } from './routes/app/monitoring/analytics'
import { Route as AppIndividualsIndividualIdRouteImport } from './routes/app/individuals.$individualId'
import { Route as AppConfigSystemRouteImport } from './routes/app/config/system'
import { Route as AppConfigProcessingRouteImport } from './routes/app/config/processing'
import { Route as AppConfigPipelinesRouteImport } from './routes/app/config/pipelines'
import { Route as AppConfigNetworkRouteImport } from './routes/app/config/network'
import { Route as AppConfigModelsRouteImport } from './routes/app/config/models'
import { Route as AppConfigDataSourcesRouteImport } from './routes/app/config/data-sources'
import { Route as AppConfigAdvancedRouteImport } from './routes/app/config/advanced'
import { Route as AppConceptSchemesSchemeIdRouteImport } from './routes/app/concept-schemes.$schemeId'
import { Route as AppClassesClassIdRouteImport } from './routes/app/classes.$classId'
import { Route as AppConfigPipelinesIndexRouteImport } from './routes/app/config/pipelines.index'
import { Route as AppConfigPipelinesPipelineTypeRouteImport } from './routes/app/config/pipelines.$pipelineType'
import { Route as AppConfigPipelinesPipelineTypeIndexRouteImport } from './routes/app/config/pipelines.$pipelineType.index'
import { Route as AppConfigPipelinesPipelineTypeCreateRouteImport } from './routes/app/config/pipelines.$pipelineType.create'
import { Route as AppConfigPipelinesPipelineTypeTestFlavorIdRouteImport } from './routes/app/config/pipelines.$pipelineType.test.$flavorId'
import { Route as AppConfigPipelinesPipelineTypeEditFlavorIdRouteImport } from './routes/app/config/pipelines.$pipelineType.edit.$flavorId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxonomiesRoute = AppTaxonomiesRouteImport.update({
  id: '/taxonomies',
  path: '/taxonomies',
  getParentRoute: () => AppRoute,
} as any)
const AppRelationshipsRoute = AppRelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertiesRoute = AppPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppIndividualsRoute = AppIndividualsRouteImport.update({
  id: '/individuals',
  path: '/individuals',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppConceptSchemesRoute = AppConceptSchemesRouteImport.update({
  id: '/concept-schemes',
  path: '/concept-schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxonomiesIndexRoute = AppTaxonomiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTaxonomiesRoute,
} as any)
const AppReferenceIndexRoute = AppReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => AppRoute,
} as any)
const AppIndividualsIndexRoute = AppIndividualsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIndividualsRoute,
} as any)
const AppConfigIndexRoute = AppConfigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConceptSchemesIndexRoute = AppConceptSchemesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConceptSchemesRoute,
} as any)
const AppClassesIndexRoute = AppClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClassesRoute,
} as any)
const AppTaxonomiesTaxonomyIdRoute = AppTaxonomiesTaxonomyIdRouteImport.update({
  id: '/$taxonomyId',
  path: '/$taxonomyId',
  getParentRoute: () => AppTaxonomiesRoute,
} as any)
const AppReferenceSearchRoute = AppReferenceSearchRouteImport.update({
  id: '/reference/search',
  path: '/reference/search',
  getParentRoute: () => AppRoute,
} as any)
const AppReferenceRagTestRoute = AppReferenceRagTestRouteImport.update({
  id: '/reference/rag-test',
  path: '/reference/rag-test',
  getParentRoute: () => AppRoute,
} as any)
const AppReferencePropertiesRoute = AppReferencePropertiesRouteImport.update({
  id: '/reference/properties',
  path: '/reference/properties',
  getParentRoute: () => AppRoute,
} as any)
const AppRagTestRunnerRoute = AppRagTestRunnerRouteImport.update({
  id: '/rag/test-runner',
  path: '/rag/test-runner',
  getParentRoute: () => AppRoute,
} as any)
const AppRagPipelineComparisonRoute =
  AppRagPipelineComparisonRouteImport.update({
    id: '/rag/pipeline-comparison',
    path: '/rag/pipeline-comparison',
    getParentRoute: () => AppRoute,
  } as any)
const AppRagExperimentsRoute = AppRagExperimentsRouteImport.update({
  id: '/rag/experiments',
  path: '/rag/experiments',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringTaskManagerRoute =
  AppMonitoringTaskManagerRouteImport.update({
    id: '/monitoring/task-manager',
    path: '/monitoring/task-manager',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitoringSystemHealthRoute =
  AppMonitoringSystemHealthRouteImport.update({
    id: '/monitoring/system-health',
    path: '/monitoring/system-health',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitoringPerformanceRoute =
  AppMonitoringPerformanceRouteImport.update({
    id: '/monitoring/performance',
    path: '/monitoring/performance',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitoringLlmTraceabilityRoute =
  AppMonitoringLlmTraceabilityRouteImport.update({
    id: '/monitoring/llm-traceability',
    path: '/monitoring/llm-traceability',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitoringAnalyticsRoute = AppMonitoringAnalyticsRouteImport.update({
  id: '/monitoring/analytics',
  path: '/monitoring/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppIndividualsIndividualIdRoute =
  AppIndividualsIndividualIdRouteImport.update({
    id: '/$individualId',
    path: '/$individualId',
    getParentRoute: () => AppIndividualsRoute,
  } as any)
const AppConfigSystemRoute = AppConfigSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConfigProcessingRoute = AppConfigProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConfigPipelinesRoute = AppConfigPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConfigNetworkRoute = AppConfigNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConfigModelsRoute = AppConfigModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConfigDataSourcesRoute = AppConfigDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConfigAdvancedRoute = AppConfigAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => AppConfigRoute,
} as any)
const AppConceptSchemesSchemeIdRoute =
  AppConceptSchemesSchemeIdRouteImport.update({
    id: '/$schemeId',
    path: '/$schemeId',
    getParentRoute: () => AppConceptSchemesRoute,
  } as any)
const AppClassesClassIdRoute = AppClassesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => AppClassesRoute,
} as any)
const AppConfigPipelinesIndexRoute = AppConfigPipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfigPipelinesRoute,
} as any)
const AppConfigPipelinesPipelineTypeRoute =
  AppConfigPipelinesPipelineTypeRouteImport.update({
    id: '/$pipelineType',
    path: '/$pipelineType',
    getParentRoute: () => AppConfigPipelinesRoute,
  } as any)
const AppConfigPipelinesPipelineTypeIndexRoute =
  AppConfigPipelinesPipelineTypeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppConfigPipelinesPipelineTypeRoute,
  } as any)
const AppConfigPipelinesPipelineTypeCreateRoute =
  AppConfigPipelinesPipelineTypeCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppConfigPipelinesPipelineTypeRoute,
  } as any)
const AppConfigPipelinesPipelineTypeTestFlavorIdRoute =
  AppConfigPipelinesPipelineTypeTestFlavorIdRouteImport.update({
    id: '/test/$flavorId',
    path: '/test/$flavorId',
    getParentRoute: () => AppConfigPipelinesPipelineTypeRoute,
  } as any)
const AppConfigPipelinesPipelineTypeEditFlavorIdRoute =
  AppConfigPipelinesPipelineTypeEditFlavorIdRouteImport.update({
    id: '/edit/$flavorId',
    path: '/edit/$flavorId',
    getParentRoute: () => AppConfigPipelinesPipelineTypeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classes': typeof AppClassesRouteWithChildren
  '/app/concept-schemes': typeof AppConceptSchemesRouteWithChildren
  '/app/config': typeof AppConfigRouteWithChildren
  '/app/datasets': typeof AppDatasetsRoute
  '/app/individuals': typeof AppIndividualsRouteWithChildren
  '/app/properties': typeof AppPropertiesRoute
  '/app/relationships': typeof AppRelationshipsRoute
  '/app/taxonomies': typeof AppTaxonomiesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/concept-schemes/$schemeId': typeof AppConceptSchemesSchemeIdRoute
  '/app/config/advanced': typeof AppConfigAdvancedRoute
  '/app/config/data-sources': typeof AppConfigDataSourcesRoute
  '/app/config/models': typeof AppConfigModelsRoute
  '/app/config/network': typeof AppConfigNetworkRoute
  '/app/config/pipelines': typeof AppConfigPipelinesRouteWithChildren
  '/app/config/processing': typeof AppConfigProcessingRoute
  '/app/config/system': typeof AppConfigSystemRoute
  '/app/individuals/$individualId': typeof AppIndividualsIndividualIdRoute
  '/app/monitoring/analytics': typeof AppMonitoringAnalyticsRoute
  '/app/monitoring/llm-traceability': typeof AppMonitoringLlmTraceabilityRoute
  '/app/monitoring/performance': typeof AppMonitoringPerformanceRoute
  '/app/monitoring/system-health': typeof AppMonitoringSystemHealthRoute
  '/app/monitoring/task-manager': typeof AppMonitoringTaskManagerRoute
  '/app/rag/experiments': typeof AppRagExperimentsRoute
  '/app/rag/pipeline-comparison': typeof AppRagPipelineComparisonRoute
  '/app/rag/test-runner': typeof AppRagTestRunnerRoute
  '/app/reference/properties': typeof AppReferencePropertiesRoute
  '/app/reference/rag-test': typeof AppReferenceRagTestRoute
  '/app/reference/search': typeof AppReferenceSearchRoute
  '/app/taxonomies/$taxonomyId': typeof AppTaxonomiesTaxonomyIdRoute
  '/app/classes/': typeof AppClassesIndexRoute
  '/app/concept-schemes/': typeof AppConceptSchemesIndexRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/individuals/': typeof AppIndividualsIndexRoute
  '/app/reference': typeof AppReferenceIndexRoute
  '/app/taxonomies/': typeof AppTaxonomiesIndexRoute
  '/app/config/pipelines/$pipelineType': typeof AppConfigPipelinesPipelineTypeRouteWithChildren
  '/app/config/pipelines/': typeof AppConfigPipelinesIndexRoute
  '/app/config/pipelines/$pipelineType/create': typeof AppConfigPipelinesPipelineTypeCreateRoute
  '/app/config/pipelines/$pipelineType/': typeof AppConfigPipelinesPipelineTypeIndexRoute
  '/app/config/pipelines/$pipelineType/edit/$flavorId': typeof AppConfigPipelinesPipelineTypeEditFlavorIdRoute
  '/app/config/pipelines/$pipelineType/test/$flavorId': typeof AppConfigPipelinesPipelineTypeTestFlavorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/datasets': typeof AppDatasetsRoute
  '/app/properties': typeof AppPropertiesRoute
  '/app/relationships': typeof AppRelationshipsRoute
  '/app': typeof AppIndexRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/concept-schemes/$schemeId': typeof AppConceptSchemesSchemeIdRoute
  '/app/config/advanced': typeof AppConfigAdvancedRoute
  '/app/config/data-sources': typeof AppConfigDataSourcesRoute
  '/app/config/models': typeof AppConfigModelsRoute
  '/app/config/network': typeof AppConfigNetworkRoute
  '/app/config/processing': typeof AppConfigProcessingRoute
  '/app/config/system': typeof AppConfigSystemRoute
  '/app/individuals/$individualId': typeof AppIndividualsIndividualIdRoute
  '/app/monitoring/analytics': typeof AppMonitoringAnalyticsRoute
  '/app/monitoring/llm-traceability': typeof AppMonitoringLlmTraceabilityRoute
  '/app/monitoring/performance': typeof AppMonitoringPerformanceRoute
  '/app/monitoring/system-health': typeof AppMonitoringSystemHealthRoute
  '/app/monitoring/task-manager': typeof AppMonitoringTaskManagerRoute
  '/app/rag/experiments': typeof AppRagExperimentsRoute
  '/app/rag/pipeline-comparison': typeof AppRagPipelineComparisonRoute
  '/app/rag/test-runner': typeof AppRagTestRunnerRoute
  '/app/reference/properties': typeof AppReferencePropertiesRoute
  '/app/reference/rag-test': typeof AppReferenceRagTestRoute
  '/app/reference/search': typeof AppReferenceSearchRoute
  '/app/taxonomies/$taxonomyId': typeof AppTaxonomiesTaxonomyIdRoute
  '/app/classes': typeof AppClassesIndexRoute
  '/app/concept-schemes': typeof AppConceptSchemesIndexRoute
  '/app/config': typeof AppConfigIndexRoute
  '/app/individuals': typeof AppIndividualsIndexRoute
  '/app/reference': typeof AppReferenceIndexRoute
  '/app/taxonomies': typeof AppTaxonomiesIndexRoute
  '/app/config/pipelines': typeof AppConfigPipelinesIndexRoute
  '/app/config/pipelines/$pipelineType/create': typeof AppConfigPipelinesPipelineTypeCreateRoute
  '/app/config/pipelines/$pipelineType': typeof AppConfigPipelinesPipelineTypeIndexRoute
  '/app/config/pipelines/$pipelineType/edit/$flavorId': typeof AppConfigPipelinesPipelineTypeEditFlavorIdRoute
  '/app/config/pipelines/$pipelineType/test/$flavorId': typeof AppConfigPipelinesPipelineTypeTestFlavorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classes': typeof AppClassesRouteWithChildren
  '/app/concept-schemes': typeof AppConceptSchemesRouteWithChildren
  '/app/config': typeof AppConfigRouteWithChildren
  '/app/datasets': typeof AppDatasetsRoute
  '/app/individuals': typeof AppIndividualsRouteWithChildren
  '/app/properties': typeof AppPropertiesRoute
  '/app/relationships': typeof AppRelationshipsRoute
  '/app/taxonomies': typeof AppTaxonomiesRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/concept-schemes/$schemeId': typeof AppConceptSchemesSchemeIdRoute
  '/app/config/advanced': typeof AppConfigAdvancedRoute
  '/app/config/data-sources': typeof AppConfigDataSourcesRoute
  '/app/config/models': typeof AppConfigModelsRoute
  '/app/config/network': typeof AppConfigNetworkRoute
  '/app/config/pipelines': typeof AppConfigPipelinesRouteWithChildren
  '/app/config/processing': typeof AppConfigProcessingRoute
  '/app/config/system': typeof AppConfigSystemRoute
  '/app/individuals/$individualId': typeof AppIndividualsIndividualIdRoute
  '/app/monitoring/analytics': typeof AppMonitoringAnalyticsRoute
  '/app/monitoring/llm-traceability': typeof AppMonitoringLlmTraceabilityRoute
  '/app/monitoring/performance': typeof AppMonitoringPerformanceRoute
  '/app/monitoring/system-health': typeof AppMonitoringSystemHealthRoute
  '/app/monitoring/task-manager': typeof AppMonitoringTaskManagerRoute
  '/app/rag/experiments': typeof AppRagExperimentsRoute
  '/app/rag/pipeline-comparison': typeof AppRagPipelineComparisonRoute
  '/app/rag/test-runner': typeof AppRagTestRunnerRoute
  '/app/reference/properties': typeof AppReferencePropertiesRoute
  '/app/reference/rag-test': typeof AppReferenceRagTestRoute
  '/app/reference/search': typeof AppReferenceSearchRoute
  '/app/taxonomies/$taxonomyId': typeof AppTaxonomiesTaxonomyIdRoute
  '/app/classes/': typeof AppClassesIndexRoute
  '/app/concept-schemes/': typeof AppConceptSchemesIndexRoute
  '/app/config/': typeof AppConfigIndexRoute
  '/app/individuals/': typeof AppIndividualsIndexRoute
  '/app/reference/': typeof AppReferenceIndexRoute
  '/app/taxonomies/': typeof AppTaxonomiesIndexRoute
  '/app/config/pipelines/$pipelineType': typeof AppConfigPipelinesPipelineTypeRouteWithChildren
  '/app/config/pipelines/': typeof AppConfigPipelinesIndexRoute
  '/app/config/pipelines/$pipelineType/create': typeof AppConfigPipelinesPipelineTypeCreateRoute
  '/app/config/pipelines/$pipelineType/': typeof AppConfigPipelinesPipelineTypeIndexRoute
  '/app/config/pipelines/$pipelineType/edit/$flavorId': typeof AppConfigPipelinesPipelineTypeEditFlavorIdRoute
  '/app/config/pipelines/$pipelineType/test/$flavorId': typeof AppConfigPipelinesPipelineTypeTestFlavorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/classes'
    | '/app/concept-schemes'
    | '/app/config'
    | '/app/datasets'
    | '/app/individuals'
    | '/app/properties'
    | '/app/relationships'
    | '/app/taxonomies'
    | '/app/'
    | '/app/classes/$classId'
    | '/app/concept-schemes/$schemeId'
    | '/app/config/advanced'
    | '/app/config/data-sources'
    | '/app/config/models'
    | '/app/config/network'
    | '/app/config/pipelines'
    | '/app/config/processing'
    | '/app/config/system'
    | '/app/individuals/$individualId'
    | '/app/monitoring/analytics'
    | '/app/monitoring/llm-traceability'
    | '/app/monitoring/performance'
    | '/app/monitoring/system-health'
    | '/app/monitoring/task-manager'
    | '/app/rag/experiments'
    | '/app/rag/pipeline-comparison'
    | '/app/rag/test-runner'
    | '/app/reference/properties'
    | '/app/reference/rag-test'
    | '/app/reference/search'
    | '/app/taxonomies/$taxonomyId'
    | '/app/classes/'
    | '/app/concept-schemes/'
    | '/app/config/'
    | '/app/individuals/'
    | '/app/reference'
    | '/app/taxonomies/'
    | '/app/config/pipelines/$pipelineType'
    | '/app/config/pipelines/'
    | '/app/config/pipelines/$pipelineType/create'
    | '/app/config/pipelines/$pipelineType/'
    | '/app/config/pipelines/$pipelineType/edit/$flavorId'
    | '/app/config/pipelines/$pipelineType/test/$flavorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/datasets'
    | '/app/properties'
    | '/app/relationships'
    | '/app'
    | '/app/classes/$classId'
    | '/app/concept-schemes/$schemeId'
    | '/app/config/advanced'
    | '/app/config/data-sources'
    | '/app/config/models'
    | '/app/config/network'
    | '/app/config/processing'
    | '/app/config/system'
    | '/app/individuals/$individualId'
    | '/app/monitoring/analytics'
    | '/app/monitoring/llm-traceability'
    | '/app/monitoring/performance'
    | '/app/monitoring/system-health'
    | '/app/monitoring/task-manager'
    | '/app/rag/experiments'
    | '/app/rag/pipeline-comparison'
    | '/app/rag/test-runner'
    | '/app/reference/properties'
    | '/app/reference/rag-test'
    | '/app/reference/search'
    | '/app/taxonomies/$taxonomyId'
    | '/app/classes'
    | '/app/concept-schemes'
    | '/app/config'
    | '/app/individuals'
    | '/app/reference'
    | '/app/taxonomies'
    | '/app/config/pipelines'
    | '/app/config/pipelines/$pipelineType/create'
    | '/app/config/pipelines/$pipelineType'
    | '/app/config/pipelines/$pipelineType/edit/$flavorId'
    | '/app/config/pipelines/$pipelineType/test/$flavorId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/classes'
    | '/app/concept-schemes'
    | '/app/config'
    | '/app/datasets'
    | '/app/individuals'
    | '/app/properties'
    | '/app/relationships'
    | '/app/taxonomies'
    | '/app/'
    | '/app/classes/$classId'
    | '/app/concept-schemes/$schemeId'
    | '/app/config/advanced'
    | '/app/config/data-sources'
    | '/app/config/models'
    | '/app/config/network'
    | '/app/config/pipelines'
    | '/app/config/processing'
    | '/app/config/system'
    | '/app/individuals/$individualId'
    | '/app/monitoring/analytics'
    | '/app/monitoring/llm-traceability'
    | '/app/monitoring/performance'
    | '/app/monitoring/system-health'
    | '/app/monitoring/task-manager'
    | '/app/rag/experiments'
    | '/app/rag/pipeline-comparison'
    | '/app/rag/test-runner'
    | '/app/reference/properties'
    | '/app/reference/rag-test'
    | '/app/reference/search'
    | '/app/taxonomies/$taxonomyId'
    | '/app/classes/'
    | '/app/concept-schemes/'
    | '/app/config/'
    | '/app/individuals/'
    | '/app/reference/'
    | '/app/taxonomies/'
    | '/app/config/pipelines/$pipelineType'
    | '/app/config/pipelines/'
    | '/app/config/pipelines/$pipelineType/create'
    | '/app/config/pipelines/$pipelineType/'
    | '/app/config/pipelines/$pipelineType/edit/$flavorId'
    | '/app/config/pipelines/$pipelineType/test/$flavorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taxonomies': {
      id: '/app/taxonomies'
      path: '/taxonomies'
      fullPath: '/app/taxonomies'
      preLoaderRoute: typeof AppTaxonomiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relationships': {
      id: '/app/relationships'
      path: '/relationships'
      fullPath: '/app/relationships'
      preLoaderRoute: typeof AppRelationshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/properties': {
      id: '/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AppPropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/individuals': {
      id: '/app/individuals'
      path: '/individuals'
      fullPath: '/app/individuals'
      preLoaderRoute: typeof AppIndividualsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets': {
      id: '/app/datasets'
      path: '/datasets'
      fullPath: '/app/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/config': {
      id: '/app/config'
      path: '/config'
      fullPath: '/app/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/concept-schemes': {
      id: '/app/concept-schemes'
      path: '/concept-schemes'
      fullPath: '/app/concept-schemes'
      preLoaderRoute: typeof AppConceptSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taxonomies/': {
      id: '/app/taxonomies/'
      path: '/'
      fullPath: '/app/taxonomies/'
      preLoaderRoute: typeof AppTaxonomiesIndexRouteImport
      parentRoute: typeof AppTaxonomiesRoute
    }
    '/app/reference/': {
      id: '/app/reference/'
      path: '/reference'
      fullPath: '/app/reference'
      preLoaderRoute: typeof AppReferenceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/individuals/': {
      id: '/app/individuals/'
      path: '/'
      fullPath: '/app/individuals/'
      preLoaderRoute: typeof AppIndividualsIndexRouteImport
      parentRoute: typeof AppIndividualsRoute
    }
    '/app/config/': {
      id: '/app/config/'
      path: '/'
      fullPath: '/app/config/'
      preLoaderRoute: typeof AppConfigIndexRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/concept-schemes/': {
      id: '/app/concept-schemes/'
      path: '/'
      fullPath: '/app/concept-schemes/'
      preLoaderRoute: typeof AppConceptSchemesIndexRouteImport
      parentRoute: typeof AppConceptSchemesRoute
    }
    '/app/classes/': {
      id: '/app/classes/'
      path: '/'
      fullPath: '/app/classes/'
      preLoaderRoute: typeof AppClassesIndexRouteImport
      parentRoute: typeof AppClassesRoute
    }
    '/app/taxonomies/$taxonomyId': {
      id: '/app/taxonomies/$taxonomyId'
      path: '/$taxonomyId'
      fullPath: '/app/taxonomies/$taxonomyId'
      preLoaderRoute: typeof AppTaxonomiesTaxonomyIdRouteImport
      parentRoute: typeof AppTaxonomiesRoute
    }
    '/app/reference/search': {
      id: '/app/reference/search'
      path: '/reference/search'
      fullPath: '/app/reference/search'
      preLoaderRoute: typeof AppReferenceSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reference/rag-test': {
      id: '/app/reference/rag-test'
      path: '/reference/rag-test'
      fullPath: '/app/reference/rag-test'
      preLoaderRoute: typeof AppReferenceRagTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reference/properties': {
      id: '/app/reference/properties'
      path: '/reference/properties'
      fullPath: '/app/reference/properties'
      preLoaderRoute: typeof AppReferencePropertiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rag/test-runner': {
      id: '/app/rag/test-runner'
      path: '/rag/test-runner'
      fullPath: '/app/rag/test-runner'
      preLoaderRoute: typeof AppRagTestRunnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rag/pipeline-comparison': {
      id: '/app/rag/pipeline-comparison'
      path: '/rag/pipeline-comparison'
      fullPath: '/app/rag/pipeline-comparison'
      preLoaderRoute: typeof AppRagPipelineComparisonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rag/experiments': {
      id: '/app/rag/experiments'
      path: '/rag/experiments'
      fullPath: '/app/rag/experiments'
      preLoaderRoute: typeof AppRagExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring/task-manager': {
      id: '/app/monitoring/task-manager'
      path: '/monitoring/task-manager'
      fullPath: '/app/monitoring/task-manager'
      preLoaderRoute: typeof AppMonitoringTaskManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring/system-health': {
      id: '/app/monitoring/system-health'
      path: '/monitoring/system-health'
      fullPath: '/app/monitoring/system-health'
      preLoaderRoute: typeof AppMonitoringSystemHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring/performance': {
      id: '/app/monitoring/performance'
      path: '/monitoring/performance'
      fullPath: '/app/monitoring/performance'
      preLoaderRoute: typeof AppMonitoringPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring/llm-traceability': {
      id: '/app/monitoring/llm-traceability'
      path: '/monitoring/llm-traceability'
      fullPath: '/app/monitoring/llm-traceability'
      preLoaderRoute: typeof AppMonitoringLlmTraceabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/monitoring/analytics': {
      id: '/app/monitoring/analytics'
      path: '/monitoring/analytics'
      fullPath: '/app/monitoring/analytics'
      preLoaderRoute: typeof AppMonitoringAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/individuals/$individualId': {
      id: '/app/individuals/$individualId'
      path: '/$individualId'
      fullPath: '/app/individuals/$individualId'
      preLoaderRoute: typeof AppIndividualsIndividualIdRouteImport
      parentRoute: typeof AppIndividualsRoute
    }
    '/app/config/system': {
      id: '/app/config/system'
      path: '/system'
      fullPath: '/app/config/system'
      preLoaderRoute: typeof AppConfigSystemRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/config/processing': {
      id: '/app/config/processing'
      path: '/processing'
      fullPath: '/app/config/processing'
      preLoaderRoute: typeof AppConfigProcessingRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/config/pipelines': {
      id: '/app/config/pipelines'
      path: '/pipelines'
      fullPath: '/app/config/pipelines'
      preLoaderRoute: typeof AppConfigPipelinesRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/config/network': {
      id: '/app/config/network'
      path: '/network'
      fullPath: '/app/config/network'
      preLoaderRoute: typeof AppConfigNetworkRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/config/models': {
      id: '/app/config/models'
      path: '/models'
      fullPath: '/app/config/models'
      preLoaderRoute: typeof AppConfigModelsRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/config/data-sources': {
      id: '/app/config/data-sources'
      path: '/data-sources'
      fullPath: '/app/config/data-sources'
      preLoaderRoute: typeof AppConfigDataSourcesRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/config/advanced': {
      id: '/app/config/advanced'
      path: '/advanced'
      fullPath: '/app/config/advanced'
      preLoaderRoute: typeof AppConfigAdvancedRouteImport
      parentRoute: typeof AppConfigRoute
    }
    '/app/concept-schemes/$schemeId': {
      id: '/app/concept-schemes/$schemeId'
      path: '/$schemeId'
      fullPath: '/app/concept-schemes/$schemeId'
      preLoaderRoute: typeof AppConceptSchemesSchemeIdRouteImport
      parentRoute: typeof AppConceptSchemesRoute
    }
    '/app/classes/$classId': {
      id: '/app/classes/$classId'
      path: '/$classId'
      fullPath: '/app/classes/$classId'
      preLoaderRoute: typeof AppClassesClassIdRouteImport
      parentRoute: typeof AppClassesRoute
    }
    '/app/config/pipelines/': {
      id: '/app/config/pipelines/'
      path: '/'
      fullPath: '/app/config/pipelines/'
      preLoaderRoute: typeof AppConfigPipelinesIndexRouteImport
      parentRoute: typeof AppConfigPipelinesRoute
    }
    '/app/config/pipelines/$pipelineType': {
      id: '/app/config/pipelines/$pipelineType'
      path: '/$pipelineType'
      fullPath: '/app/config/pipelines/$pipelineType'
      preLoaderRoute: typeof AppConfigPipelinesPipelineTypeRouteImport
      parentRoute: typeof AppConfigPipelinesRoute
    }
    '/app/config/pipelines/$pipelineType/': {
      id: '/app/config/pipelines/$pipelineType/'
      path: '/'
      fullPath: '/app/config/pipelines/$pipelineType/'
      preLoaderRoute: typeof AppConfigPipelinesPipelineTypeIndexRouteImport
      parentRoute: typeof AppConfigPipelinesPipelineTypeRoute
    }
    '/app/config/pipelines/$pipelineType/create': {
      id: '/app/config/pipelines/$pipelineType/create'
      path: '/create'
      fullPath: '/app/config/pipelines/$pipelineType/create'
      preLoaderRoute: typeof AppConfigPipelinesPipelineTypeCreateRouteImport
      parentRoute: typeof AppConfigPipelinesPipelineTypeRoute
    }
    '/app/config/pipelines/$pipelineType/test/$flavorId': {
      id: '/app/config/pipelines/$pipelineType/test/$flavorId'
      path: '/test/$flavorId'
      fullPath: '/app/config/pipelines/$pipelineType/test/$flavorId'
      preLoaderRoute: typeof AppConfigPipelinesPipelineTypeTestFlavorIdRouteImport
      parentRoute: typeof AppConfigPipelinesPipelineTypeRoute
    }
    '/app/config/pipelines/$pipelineType/edit/$flavorId': {
      id: '/app/config/pipelines/$pipelineType/edit/$flavorId'
      path: '/edit/$flavorId'
      fullPath: '/app/config/pipelines/$pipelineType/edit/$flavorId'
      preLoaderRoute: typeof AppConfigPipelinesPipelineTypeEditFlavorIdRouteImport
      parentRoute: typeof AppConfigPipelinesPipelineTypeRoute
    }
  }
}

interface AppClassesRouteChildren {
  AppClassesClassIdRoute: typeof AppClassesClassIdRoute
  AppClassesIndexRoute: typeof AppClassesIndexRoute
}

const AppClassesRouteChildren: AppClassesRouteChildren = {
  AppClassesClassIdRoute: AppClassesClassIdRoute,
  AppClassesIndexRoute: AppClassesIndexRoute,
}

const AppClassesRouteWithChildren = AppClassesRoute._addFileChildren(
  AppClassesRouteChildren,
)

interface AppConceptSchemesRouteChildren {
  AppConceptSchemesSchemeIdRoute: typeof AppConceptSchemesSchemeIdRoute
  AppConceptSchemesIndexRoute: typeof AppConceptSchemesIndexRoute
}

const AppConceptSchemesRouteChildren: AppConceptSchemesRouteChildren = {
  AppConceptSchemesSchemeIdRoute: AppConceptSchemesSchemeIdRoute,
  AppConceptSchemesIndexRoute: AppConceptSchemesIndexRoute,
}

const AppConceptSchemesRouteWithChildren =
  AppConceptSchemesRoute._addFileChildren(AppConceptSchemesRouteChildren)

interface AppConfigPipelinesPipelineTypeRouteChildren {
  AppConfigPipelinesPipelineTypeCreateRoute: typeof AppConfigPipelinesPipelineTypeCreateRoute
  AppConfigPipelinesPipelineTypeIndexRoute: typeof AppConfigPipelinesPipelineTypeIndexRoute
  AppConfigPipelinesPipelineTypeEditFlavorIdRoute: typeof AppConfigPipelinesPipelineTypeEditFlavorIdRoute
  AppConfigPipelinesPipelineTypeTestFlavorIdRoute: typeof AppConfigPipelinesPipelineTypeTestFlavorIdRoute
}

const AppConfigPipelinesPipelineTypeRouteChildren: AppConfigPipelinesPipelineTypeRouteChildren =
  {
    AppConfigPipelinesPipelineTypeCreateRoute:
      AppConfigPipelinesPipelineTypeCreateRoute,
    AppConfigPipelinesPipelineTypeIndexRoute:
      AppConfigPipelinesPipelineTypeIndexRoute,
    AppConfigPipelinesPipelineTypeEditFlavorIdRoute:
      AppConfigPipelinesPipelineTypeEditFlavorIdRoute,
    AppConfigPipelinesPipelineTypeTestFlavorIdRoute:
      AppConfigPipelinesPipelineTypeTestFlavorIdRoute,
  }

const AppConfigPipelinesPipelineTypeRouteWithChildren =
  AppConfigPipelinesPipelineTypeRoute._addFileChildren(
    AppConfigPipelinesPipelineTypeRouteChildren,
  )

interface AppConfigPipelinesRouteChildren {
  AppConfigPipelinesPipelineTypeRoute: typeof AppConfigPipelinesPipelineTypeRouteWithChildren
  AppConfigPipelinesIndexRoute: typeof AppConfigPipelinesIndexRoute
}

const AppConfigPipelinesRouteChildren: AppConfigPipelinesRouteChildren = {
  AppConfigPipelinesPipelineTypeRoute:
    AppConfigPipelinesPipelineTypeRouteWithChildren,
  AppConfigPipelinesIndexRoute: AppConfigPipelinesIndexRoute,
}

const AppConfigPipelinesRouteWithChildren =
  AppConfigPipelinesRoute._addFileChildren(AppConfigPipelinesRouteChildren)

interface AppConfigRouteChildren {
  AppConfigAdvancedRoute: typeof AppConfigAdvancedRoute
  AppConfigDataSourcesRoute: typeof AppConfigDataSourcesRoute
  AppConfigModelsRoute: typeof AppConfigModelsRoute
  AppConfigNetworkRoute: typeof AppConfigNetworkRoute
  AppConfigPipelinesRoute: typeof AppConfigPipelinesRouteWithChildren
  AppConfigProcessingRoute: typeof AppConfigProcessingRoute
  AppConfigSystemRoute: typeof AppConfigSystemRoute
  AppConfigIndexRoute: typeof AppConfigIndexRoute
}

const AppConfigRouteChildren: AppConfigRouteChildren = {
  AppConfigAdvancedRoute: AppConfigAdvancedRoute,
  AppConfigDataSourcesRoute: AppConfigDataSourcesRoute,
  AppConfigModelsRoute: AppConfigModelsRoute,
  AppConfigNetworkRoute: AppConfigNetworkRoute,
  AppConfigPipelinesRoute: AppConfigPipelinesRouteWithChildren,
  AppConfigProcessingRoute: AppConfigProcessingRoute,
  AppConfigSystemRoute: AppConfigSystemRoute,
  AppConfigIndexRoute: AppConfigIndexRoute,
}

const AppConfigRouteWithChildren = AppConfigRoute._addFileChildren(
  AppConfigRouteChildren,
)

interface AppIndividualsRouteChildren {
  AppIndividualsIndividualIdRoute: typeof AppIndividualsIndividualIdRoute
  AppIndividualsIndexRoute: typeof AppIndividualsIndexRoute
}

const AppIndividualsRouteChildren: AppIndividualsRouteChildren = {
  AppIndividualsIndividualIdRoute: AppIndividualsIndividualIdRoute,
  AppIndividualsIndexRoute: AppIndividualsIndexRoute,
}

const AppIndividualsRouteWithChildren = AppIndividualsRoute._addFileChildren(
  AppIndividualsRouteChildren,
)

interface AppTaxonomiesRouteChildren {
  AppTaxonomiesTaxonomyIdRoute: typeof AppTaxonomiesTaxonomyIdRoute
  AppTaxonomiesIndexRoute: typeof AppTaxonomiesIndexRoute
}

const AppTaxonomiesRouteChildren: AppTaxonomiesRouteChildren = {
  AppTaxonomiesTaxonomyIdRoute: AppTaxonomiesTaxonomyIdRoute,
  AppTaxonomiesIndexRoute: AppTaxonomiesIndexRoute,
}

const AppTaxonomiesRouteWithChildren = AppTaxonomiesRoute._addFileChildren(
  AppTaxonomiesRouteChildren,
)

interface AppRouteChildren {
  AppClassesRoute: typeof AppClassesRouteWithChildren
  AppConceptSchemesRoute: typeof AppConceptSchemesRouteWithChildren
  AppConfigRoute: typeof AppConfigRouteWithChildren
  AppDatasetsRoute: typeof AppDatasetsRoute
  AppIndividualsRoute: typeof AppIndividualsRouteWithChildren
  AppPropertiesRoute: typeof AppPropertiesRoute
  AppRelationshipsRoute: typeof AppRelationshipsRoute
  AppTaxonomiesRoute: typeof AppTaxonomiesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppMonitoringAnalyticsRoute: typeof AppMonitoringAnalyticsRoute
  AppMonitoringLlmTraceabilityRoute: typeof AppMonitoringLlmTraceabilityRoute
  AppMonitoringPerformanceRoute: typeof AppMonitoringPerformanceRoute
  AppMonitoringSystemHealthRoute: typeof AppMonitoringSystemHealthRoute
  AppMonitoringTaskManagerRoute: typeof AppMonitoringTaskManagerRoute
  AppRagExperimentsRoute: typeof AppRagExperimentsRoute
  AppRagPipelineComparisonRoute: typeof AppRagPipelineComparisonRoute
  AppRagTestRunnerRoute: typeof AppRagTestRunnerRoute
  AppReferencePropertiesRoute: typeof AppReferencePropertiesRoute
  AppReferenceRagTestRoute: typeof AppReferenceRagTestRoute
  AppReferenceSearchRoute: typeof AppReferenceSearchRoute
  AppReferenceIndexRoute: typeof AppReferenceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClassesRoute: AppClassesRouteWithChildren,
  AppConceptSchemesRoute: AppConceptSchemesRouteWithChildren,
  AppConfigRoute: AppConfigRouteWithChildren,
  AppDatasetsRoute: AppDatasetsRoute,
  AppIndividualsRoute: AppIndividualsRouteWithChildren,
  AppPropertiesRoute: AppPropertiesRoute,
  AppRelationshipsRoute: AppRelationshipsRoute,
  AppTaxonomiesRoute: AppTaxonomiesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppMonitoringAnalyticsRoute: AppMonitoringAnalyticsRoute,
  AppMonitoringLlmTraceabilityRoute: AppMonitoringLlmTraceabilityRoute,
  AppMonitoringPerformanceRoute: AppMonitoringPerformanceRoute,
  AppMonitoringSystemHealthRoute: AppMonitoringSystemHealthRoute,
  AppMonitoringTaskManagerRoute: AppMonitoringTaskManagerRoute,
  AppRagExperimentsRoute: AppRagExperimentsRoute,
  AppRagPipelineComparisonRoute: AppRagPipelineComparisonRoute,
  AppRagTestRunnerRoute: AppRagTestRunnerRoute,
  AppReferencePropertiesRoute: AppReferencePropertiesRoute,
  AppReferenceRagTestRoute: AppReferenceRagTestRoute,
  AppReferenceSearchRoute: AppReferenceSearchRoute,
  AppReferenceIndexRoute: AppReferenceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
